### ISSUE TITLE
Open Massa Station home page at the click

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#1015]
**Context**
Currently, on all OS, when you installed Massa Station you can see Massa Station icon on your desktop or on your application folder, then when you double click on icon an icon tray appears on your app menu and finally you can navigate this icon tray to open Massa Station home page. 

The objective of this ticket is to transform this user flow into: 
As a user, when I installed massa station I can see Massa Station icon on my desktop or on my application folder, then when I double click on the icon: an icon tray appears on my app menu **AND station.massa/home opens in my default browser at the same time.**

--> open the browser when user double click on the icons AND launch the icon tray to make this flow more instinctive.

**User flow**
See above

**How to**

- [ ] Update the installation script for all OS
- [ ] Update the e2e if they already exist

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
Test following the above user flow

**Comment by Thykof** [comment]
Technically speaking, I am not sure we will need to update the installation scripts (good news)

**Comment by longgamma-massa** [comment]
@thomas-senechal @Thykof how to Q/A?

**Comment by thomas-senechal** [comment]
> @thomas-senechal @Thykof how to Q/A?

Hi !

1. Download MassaStation
2. Install MassaStation
3. Start MassaStation
4. The homepage should be opened automatically

**Comment by longgamma-massa** [comment]
Works from MacOS M1. Opens at the preferred browser. Nice @thomas-senechal! This needs to be checked for other MacOS, Linux and Win I suppose. @Thykof can you identify who can review those?

**Comment by thomas-senechal** [comment]
I can confirm that it is working on Windows

Didn't checked on Linux tho

**Comment by Thykof** [comment]
I confirm it works on Ubuntu too

**Comment by longgamma-massa** [comment]
so we need MacOS intel?

**Comment by Thykof** [comment]
Preferably yes
