### ISSUE TITLE
Search page - reduce loading time of the websites

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#1017]
**Context**
Today the search page takes a lot of time to be displayed. Way too much time compare to today's web standard, we should try to optimise this flow and try to reach the web2 standards which is about 2 to 5 sec max. 

The objective of this ticket is to analyse what takes today, discuss and agree on a solution.

**User flow**
As a user, when I go on the search page, I want to wait max 5 sec to see some websites displayed on the page.
Note: 
* 5 sec is up to discussion but as a fyi it's the standard we should try to reach
* some websites mean that the page shouldn't load for more time as it is now and so it is acceptable to only display NOT all websites.

**How to**

- [x] Analyse current situation and understand what takes time
- [x] Identify potential solutions 
- [x] #1023
- [x] Discuss and agree on which solution to implement with Massa Station lead dev (Pierre S)
- [x] Implement the solution (fetch all favicons and website data in parallels)

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
Follow user flow above.

**Comment by SlnPons** [comment]
See prelims analysis here: https://github.com/massalabs/station/issues/1004

**Comment by SlnPons** [comment]
Note that this is a potential solution but probably not the easiest / most valuable to implement: https://github.com/massalabs/station/issues/855

**Comment by SlnPons** [comment]
@B-Naoufal can you follow the DoR before moving this issue in progress please. Keep repeating the same thing but please let's follow the basic process to assure visibility and avoid rework 🙏

**Comment by longgamma-massa** [comment]
@B-Naoufal I got results almost instantly on the search page. Is there anything else I should Q/A?

**Comment by B-Naoufal** [comment]
@longgamma-massa no i already added the parallelizing to fetch websites very fast and added a step in ci to remove the create dummy websites, so everything is already tested !

**Comment by longgamma-massa** [comment]
super thanks
