### ISSUE TITLE
Register Massa Labs as Apple dev to remove installation warning

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#1019]
**Context**
When installing Massa Station, MacOS users have to accept the run it at their own risk because Massa Labs is not a registered developer. We should register on Apple to remove this warning and improve Massa Station installation. 
Currently they have to follow: https://support.apple.com/en-us/HT202491

How to get registered on Apple: https://developer.apple.com/support/developer-id/ 
$US99

**Comment by AurelienFT** [comment]
@longgamma-massa
Hello,

I think this is a big problem. Personally when this appears I don't launch the software and it could create fear to a lot of users.

**Comment by longgamma-massa** [comment]
@AurelienFT noted, thanks for the feedback, sir!

@Thykof (@gregLibert cc) I will investigate a bit for this first. I'll sync with you to identify the requirements after. Treat it as Nice-to-have for the next release.

**Comment by gregLibert** [comment]
@longgamma-massa as discussed:
- we have the same subject for windows. But considering our user-base, the windows task has a higher priority
- we tried some stuff months ago without success on Mac. Once you have a sufficient overview, please go back to @Thykof for the take aways of the first try.

**Comment by longgamma-massa** [comment]
@gregLibert we should be able to register at Apple Dev ourselves. We'll need to prove the legal identity, but steps about i will be clear after creation of Apple ID for our organization

**Comment by Thykof** [comment]
this is interesting: https://github.com/marketplace/actions/wails-build-action#macos-code-signing

**Comment by longgamma-massa** [comment]
nice! Can we use it/ does it help us? :)

**Comment by Thykof** [comment]
maybe we can use it or at least inspire from the source code.

**Comment by gregLibert** [comment]
The following secret have been added to this repo:
![image](https://github.com/massalabs/station/assets/16623956/a79a168d-19af-4ce8-8433-6362bc2fd63d)

/!\ this certificate is a _Apple Development_, it's not a _Developer ID Application_ one. This means that only adhoc install will work.

**Comment by longgamma-massa** [comment]
That's great. What are the next steps for removing the certificate?

**Comment by Thykof** [comment]
We can start to see how to use this certificate on our build process, then we need a Developer ID Application Certificate
