### ISSUE TITLE
Network switch - not working on Firefox

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#1035]
**The problem(s)**

The network switch is not working on Ubuntu x Firefox. I doesn't change at all

**To Reproduce**

Use the combination of OS & browser above and see the error below in the video

https://github.com/massalabs/station/assets/109611779/ac9903fd-88af-43d2-81ad-edd3f7724edf

**Expected behavior(s)**

The network switch should work on any OS / browser combination of the [DoD](https://www.notion.so/massa-innoteam/MassaStation-85b1d05ad8df4502af7e1de50d465ae4?pvs=4#39c359bd6da14a12809f4de45c28699b)

**Screenshots**
see video above 

**MassaStation version**
V0.3.0

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - browser: firefox

**Comment by Thykof** [comment]
https://github.com/massalabs/station/pull/1093#issuecomment-1682345941

**Comment by thomas-senechal** [comment]
The bug also appeared on my Windows 11 desktop, but it's really rare and so, hard to reproduce.

**Comment by thomas-senechal** [comment]
It looks like the issue is that the request is cancelled because of the refresh that is performed before the API call even ends

**Comment by longgamma-massa** [comment]
works on MacOS. @Thykof who can test Ubuntu?

**Comment by Thykof** [comment]
Works also on Ubuntu, firefox and chrome.
