### ISSUE TITLE
Webonchain on firefox windows: no favicon in website list

### ISSUE THREAD

**Issue by Thykof** [massalabs/station#1036]
**The problem(s)**

![image](https://github.com/massalabs/station/assets/11590067/8927a1e3-fd13-4fd3-8a24-e8064d9f31a3)

On windows with browser firefox, the https navigation doesn't work yet (we have issues and PR ongoing to solve this).

The favicon is use scheme https: https://github.com/massalabs/station/blob/7a04109a7a5a8228d7f7f2eac36acce4e213e96f/int/api/websites/all.go#L158

We must use http instead.

**To Reproduce**

On windows, firefox, http://station.massa/web/search

**Expected behavior(s)**

**Screenshots**

**MassaStation version**
The version of MassaStation the bug is present in.

v0.2.5
v0.3.0

**Desktop (please complete the following information):**
 - OS: Windows
 - browser: firefox
 
 **Any other useful info**

If https work on windows+firefox, we must drop this issue.

**Comment by thomas-senechal** [comment]
Passed QA: Working perfectly
