### ISSUE TITLE
Module store - prevent the same plugin to be installed twice

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#1039]
**Context**
Currently when you have a plugin installed and that you try to installed it again using the manual installation, the installation failed without a clear message. 

We should see a clear message saying that the plugin is already installed so user knows about it.

**How to**

- [ ] Improve error message to give clear indication to end user

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
Follow user flow describe above

**Comment by Thykof** [comment]
duplicate of https://github.com/massalabs/station/issues/854

**Comment by gregLibert** [comment]
This issue should be addressed during the plugin rework. @SlnPons, please let me know if you think my cleanup was excessive.
