### ISSUE TITLE
Err is ignored

### ISSUE THREAD

**Issue by gregLibert** [massalabs/station#1040]
https://github.com/massalabs/station/blob/92b786936b05c543af6556ce1cf4d19aafbe4bb5/int/api/myplugin/execute.go#L51
https://github.com/massalabs/station/blob/92b786936b05c543af6556ce1cf4d19aafbe4bb5/int/api/myplugin/execute.go#L58

**Comment by thomas-senechal** [comment]
We don't use RemoveAlias there anymore
We only use it here : https://github.com/massalabs/station/blob/3046b23272ed586f47446e37d48ae0560ba0cb9a/pkg/plugin/manager.go#L277
And we don't ignore it anymore. 

I think we can close this issue unless we want to keep it to ensure that every errors are checked.

WDYT @Thykof @gregLibert ?
