### ISSUE TITLE
massastation compatibility not checked with the plugin

### ISSUE THREAD

**Issue by Pierregvx** [massalabs/station#1047]
**Context**
There is no check to see if massastation is compatible with the plugin for :
- an install from the store 
- when we launch a plugin

**User flow**
use an old version of massastation
install a plugin in the store 
you should get some errors when trying to access the plugin

**How to**
- [ ] add a field isCompatible in the store struct that return false if the plugin cannot be installed 
- [ ] #1049

**Technical details**
The check if the install is available could be similar to the one for the update 

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

_Originally posted by @Pierregvx in https://github.com/massalabs/station-massa-wallet/issues/494#issuecomment-1623094075_

**Comment by Thykof** [comment]
endpoint http://station.massa/plugin-store contains `iscompatible`: QA OK
