### ISSUE TITLE
display a warning in the frontend if massastation is not up to date with the plugin

### ISSUE THREAD

**Issue by Pierregvx** [massalabs/station#1049]
**Context**
As a user, I want to install a plugin from my out to date version of massa station. There is no warning even though the plugin won't be compatible
**User flow**
use an old version of massastation
install a plugin in the store 
you should get some errors when trying to access the plugin

**How to**
- check for the field `isCompatible` in the pluginStore return 
- if it is set to false, hide the download button & show a warning - see https://github.com/massalabs/station/issues/1047#issuecomment-1649692928

**Technical details**
The check if the install is available could be similar to the one for the update 

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by longgamma-massa** [comment]
@mazmassa cc designs are approved
<img width="441" alt="image" src="https://github.com/massalabs/station/assets/113043914/8b1a9e65-8453-4061-9ebb-18747db6aa5e">

Designs at: https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=4986-29859&mode=design&t=dt8uQ3KsRvdytDlP-0

**Comment by longgamma-massa** [comment]
Moved this frontend task in the next release. 

@mazmassa identify needs from designs here if current ones can't be implemented.

**Comment by longgamma-massa** [comment]
how to q/a?

**Comment by Thykof** [comment]
following PR: https://github.com/massalabs/station/pull/1152

**Comment by Thykof** [comment]
I tested by hard-coding the version of Massa Station in the source code. It work as expected.
![image](https://github.com/massalabs/station/assets/11590067/d853c8be-70a3-41ec-86f5-40a076c6e070)

**Comment by longgamma-massa** [comment]
What about my error?
