### ISSUE TITLE
Create package node/read/executereadonlycall.go

### ISSUE THREAD

**Issue by B-Naoufal** [massalabs/station#1061]
**Context**
*Needed By Assets Page : https://github.com/massalabs/station-massa-wallet/issues/539*

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*

**How to**
*List the step-by-step to get it do if needed - PM*

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by Thykof** [comment]
duplicate with https://github.com/massalabs/station/issues/1269
