### ISSUE TITLE
Add FAQ to the landing page

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/station#1062]
**Context**
Some users might face some common issues during installation, a FAQ could help them to solve those issues and answer some questions they might have really fast. 

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*

**How to**
*List the step-by-step to get it do if needed - PM*

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by gregLibert** [comment]
@longgamma-massa @SlnPons still needed ?

**Comment by thomas-senechal** [comment]
This has been partly done with [the FAQ added to the Massa Doc](https://docs.massa.net/docs/massaStation/faq). 
I guess we don't need to add an FAQ to the landing page, but that would be great to have a link to the Massa Doc somewhere on it

**Comment by longgamma-massa** [comment]
@thomas-senechal this is done, the link exists in the footer. Closing the issue
