### ISSUE TITLE
Windows Acrylic already installed error

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/station#1065]
**The problem(s)**
When installing MassaStation of Windows, we might end up with an error saying that "Service Acrylic DNS Proxy" failed to installed because it already exists. Clicking the "OK" button allows the installation to continue and MassaStation works as expected

**To Reproduce**
Need to define the first steps that caused the issue
1. ???
2. Install a newer version of MassaStation
3. See the error

**Expected behavior(s)**
The installation should work without any error

**Screenshots**
![image](https://github.com/massalabs/station/assets/44696378/cc0ad0a8-c247-43a3-8998-f4d214cb9050)

**MassaStation version**
0.3.0

**Desktop:**
 - OS: Windows
 
 **Any other useful info**
- We already know that this bug is due to [this CustomAction](https://github.com/massalabs/station/blob/8d132ccf865189009358541cae0a92e02bf49c2c/installer/windows/build_installer.py#L320C1-L327C11). The issue is that the script that we run is only a call to `AcrylicUI.exe InstallAcrylicService`, so we don't have any way to reproduce it to avoid the GUI to appear in case of error.
- A possible solution would be to add a check to see if the service is already installed before performing this action.

**Comment by thomas-senechal** [comment]
Appeared here: https://github.com/massalabs/station/issues/1055#issuecomment-1653320075

**Comment by longgamma-massa** [comment]
@gregLibert @thomas-senechal is this still an existing issue? We corresponded on it a few times. Should be addressed before Mainnet IMO.

**Comment by thomas-senechal** [comment]
> @gregLibert @thomas-senechal is this still an existing issue? We corresponded on it a few times. Should be addressed before Mainnet IMO.

Yes, this issue is still present and needs to be fixed for Mainnet even if it does not prevent users from installing MassaStation

**Comment by longgamma-massa** [comment]
This impacts audience who might have DNS proxy installed/used already. Who are those? I think it's P1 but let @gregLibert comment also

**Comment by gregLibert** [comment]
> > @gregLibert @thomas-senechal is this still an existing issue? We corresponded on it a few times. Should be addressed before Mainnet IMO.
> 
> Yes, this issue is still present and needs to be fixed for Mainnet even if it does not prevent users from installing MassaStation

What is the real consequence of the message ? Can it be safely ignored ?

**Comment by thomas-senechal** [comment]
> > > @gregLibert @thomas-senechal is this still an existing issue? We corresponded on it a few times. Should be addressed before Mainnet IMO.
> > 
> > 
> > Yes, this issue is still present and needs to be fixed for Mainnet even if it does not prevent users from installing MassaStation
> 
> What is the real consequence of the message ? Can it be safely ignored ?

No real consequences. You can click "Ok" and the installation process will continue normally. 
The issue is that it requires a user interaction and the users will face this dialog that looks like an error

**Comment by gregLibert** [comment]
This topic should be tackled when we rework the web-on-chain. @SlnPons , please feel free to tag this issue for easier reference and refinement in the future, or not 😁.
