### ISSUE TITLE
Station uninstall on ubuntu

### ISSUE THREAD

**Issue by damip** [massalabs/station#1073]
# task

Remove the second prompt during the uninstallation of Massa Station on ubuntu: https://github.com/massalabs/station/blob/e179c6ec76a2cd9a27d313966a2707f69b5e36bb/installer/deb/scripts/postrm#L70

# Bug report

The current Station uninstaller hangs the Ubuntu unistall GUI at 80%:

![image](https://github.com/massalabs/station/assets/10211103/776a5d2b-d23d-485f-90b3-51518ec18a08)

This then requires a complicated process to recover:

```
damip@damip-pc:~/massa/massa-node$ sudo apt remove massastation
[sudo] password for damip: 
Waiting for cache lock: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 862706 (packagekitd)      
Waiting for cache lock: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 862706 (packagekitd)      
Waiting for cache lock: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 862706 (packagekitd)      
Waiting for cache lock: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 862706 (packagekitd)      
Waiting for cache lock: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 862706 (packagekitd)      
Waiting for cache lock: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 862706 (packagekitd)      
^Citing for cache lock: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 862706 (packagekitd)... 6s
damip@damip-pc:~/massa/massa-node$ pkill -f packagekitd
pkill: killing pid 862706 failed: Operation not permitted
pkill: killing pid 862766 failed: Operation not permitted
damip@damip-pc:~/massa/massa-node$ sudo pkill -f packagekitd
damip@damip-pc:~/massa/massa-node$ sudo apt remove massastation
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
damip@damip-pc:~/massa/massa-node$ sudo dpkg --configure -a
Processing triggers for gnome-menus (3.36.0-1.1ubuntu1) ...
Processing triggers for man-db (2.11.2-1) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu5) ...
damip@damip-pc:~/massa/massa-node$ sudo apt remove massastation
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  massastation
0 upgraded, 0 newly installed, 1 to remove and 31 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 232353 files and directories currently installed.)
Removing massastation (0.3.0-dev) ...
This script will remove anything related to MassaStation from your system.
This includes the MassaStation App, configuration files, plugins, and every other files generated by MassaStation or it's plugins.
Are you sure you want to continue? [y/N] y
Removing DNSMasq configuration files...

Removing MassaStation configuration directory...

Removing MassaStation certificates...
MassaStation was successfully uninstalled. We're sorry to see you go.
damip@damip-pc:~/massa/massa-node$ 
```

What is happening is that the user prompt `This script will remove anything related to MassaStation from your system.
This includes the MassaStation App, configuration files, plugins, and every other files generated by MassaStation or it's plugins.
Are you sure you want to continue? [y/N] y` hangs the system when not launched from the terminal.

I think this prompt should be removed, also because as you can see above, the system already has such a prompt: 
```
The following packages will be REMOVED:
  massastation
0 upgraded, 0 newly installed, 1 to remove and 31 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
```
so I end up typing "y" twice to uninstall

**Comment by Thykof** [comment]
Hi @damip this is why we recommend to uninstall with `sudo apt remove massastation`.

The second prompt is to ask to remove all traced of Massa Station. We should list those traced and decide whether to delete them by default, hence removing the second prompt.

**Comment by damip** [comment]
TBH nobody reads the recommended way to uninstall, they just uninstall like they would do for any other app on their system :)

**Comment by Thykof** [comment]
here we can find what will be remove if we answer "y" to the second prompt: https://github.com/massalabs/station/blob/e179c6ec76a2cd9a27d313966a2707f69b5e36bb/installer/deb/scripts/postrm#L52

@longgamma-massa do we want our accounts of plugin wallet to be remove automatically when we uninstall Massa Station from Ubuntu? If yes, let's remove that 2nd prompt. If no, let's look for a better way to uninstall...

**Comment by damip** [comment]
FYI bitcoin wallet software store wallets in ~/.walletprogramname/wallets/wallet.dat so that when you uninstall, you keep your wallet

**Comment by Thykof** [comment]
Currently, on macos and windows, when user uninstall Massa Station, it remove the account yaml file without more confirmation step. So to have the same behavior on ubuntu, we will remove the second prompt.

In addition, we will find a way to keep those precious yaml files (storing them somewhere else for example) for the mainnet.

**Comment by Thykof** [comment]
QA: on ubuntu 22, uninstalled from command line asked my only one confirm prompt. Uninstalled from the "software install": success
