### ISSUE TITLE
Log permission denied prevents MassaStation from launching

### ISSUE THREAD

**Issue by drphero** [massalabs/station#1075]
**The problem(s)**
2023/08/04 14:00:58 while initializing logger: initialize global logger: open log file: open /usr/local/share/massastation/logs/massastation.log: permission denied

**To Reproduce**
Right-click the file and from the context menu, select "Open" and then click "Open" again.

**Expected behavior(s)**
Massa Station launches

**Screenshots**

**MassaStation version**
The version of MassaStation the bug is present in.

v0.3.0

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows...]
 
MacOS 12.6.8 M1
 
 **Any other useful info**

**Comment by drphero** [comment]
> Hi @drphero thank you for you feedback.
> 
> Can you run `ls -la /usr/local/share/massastation` and show me what's printed please?

`total 0
drwxr-xr-x  3 root  staff   96 Aug  4 13:57 .
drwxr-xr-x  9 root  staff  288 Aug  4 13:53 ..
drwxr-xr-x  3 root  staff   96 Aug  4 14:09 logs`

**Comment by Thykof** [comment]
Hi @drphero you should have also a `cert` directory in `/usr/local/share/massastation`.

Did you install Massa Station with the .pkg file? https://github.com/massalabs/station/releases/download/v0.3.0/massastation_0.3.0_arm64.pkg

Can you run `ls -la /usr/local/share/massastation/logs` and show me what's printed please?

**Comment by drphero** [comment]
> Hi @drphero you should have also a `cert` directory in `/usr/local/share/massastation`.
> 
> Did you install Massa Station with the .pkg file? https://github.com/massalabs/station/releases/download/v0.3.0/massastation_0.3.0_arm64.pkg
> 
> Can you run `ls -la /usr/local/share/massastation/logs` and show me what's printed please?

I have installed the pkg file, however when trying to run it, it only appears in the dock for less than a second before closing. ls -la /usr/local/share/massastation/logs shows this:

```
drwxr-xr-x  3 root  staff   96 Aug  4 14:09 .
drwxr-xr-x  5 root  staff  160 Aug  7 13:32 ..
-rw-r--r--  1 root  staff  369 Aug  4 14:09 massastation.log
```

**Comment by Thykof** [comment]
Okay thanks, can you show me what's inside that file with `/usr/local/share/massastation/logs` please?

Then, could you run again the .pkg, and before closing at the final step, hit cmd+L, chose "all logs" at the upper right menu and send me the content at ns@massa.net.

Then could you uninstall Massa Station by running: `bash -c "$(curl -fsSL https://raw.githubusercontent.com/massalabs/station/main/installer/macos/scripts/uninstall.sh)"`.

After that, you can install Massa Station and tell me if the problem still occur

**Comment by drphero** [comment]
> /usr/local/share/massastation/logs

Inside massastation.log is this:
```
2023-08-04T14:09:14.978+0200	FATAL	logger/global.go:117	Unable to read cert dir:%s
%sunable to read cert directory: /etc/massastation/certs: stat /etc/massastation/certs: no such file or directoryMassaStation can't run without a certificate directory.
			Please reinstall MassaStation using the installer at https://github.com/massalabs/station and try again.
```

Running the uninstall script and installing the pkg file seems to have worked so far. MassaStation is running - let's see if it can successfully install a node on a VPS. Also, I sent you the installation log file.

**Comment by Thykof** [comment]
The log message was written by v0.2.5 or earlier I think.

In the installation log, it look like most of the postinstall script has been skipped, @thomas-senechal I transfered the log file, WDYT?

**Comment by drphero** [comment]
> The log message was written by v0.2.5 or earlier I think.

That's very odd since I haven't tried a version other than 0.3.0. I tried Thyra quite a while ago, but it never could complete the node install. Been waiting about 20 minutes so far for the node manager to install the node on the vps.

**Comment by drphero** [comment]
Just sitting like this with no changes to the vps:

![image](https://github.com/massalabs/station/assets/14174687/db5a726b-e1c2-45fc-bb74-77bf3c63b212)

**Comment by Thykof** [comment]
Hi @drphero sorry to heard that, we haven't updated the node manager since a little while... You can open an issue here https://github.com/massalabs/station-massa-node-manager/issues/new?assignees=&labels=issue%3Abug&projects=&template=bug.md&title=

**Comment by Thykof** [comment]
I close this issue, don't hesitate to reopen it if you encounter again problems with logs folder.
