### ISSUE TITLE
404 not found on wallet module after fresh installation

### ISSUE THREAD

**Issue by litchipi** [massalabs/station#1088]
**The problem(s)**
After installing MassaStation on a fresh VM (Debian 12):
- (bonus issue) An icon is created for MassaStation, but when we click on it, it starts silently in the background (I had no idea what was happening)
- When on WebUI, after installing the Wallet module, pressing "Launch" opens a 404 page

**To Reproduce**
- Install Debian 12 on a VM
- Install MassaStation from the latest release
- Open the WebUI and install the Wallet module
- Click "Launch"
- Cry

**Expected behavior(s)**
Should Open the wallet WebUI

**Screenshots**
![image](https://github.com/massalabs/station/assets/61109829/a06ca62f-c373-45a0-8952-af59ffd93783)

**MassaStation version**
Latest `v0.3.0` release

**Desktop (please complete the following information):**
- OS Debian 12 (Virtual Machine) got from https://www.linuxvmimages.com/images/debian-12/

**Comment by litchipi** [comment]
Ping @gregLibert , I have no idea why this is happening, I used a fresh VM and followed the instructions, used the standard installation process :-(

**Comment by gregLibert** [comment]
@litchipi can you confirm this bug still exist in the last version of MS pretty please ?

**Comment by litchipi** [comment]
@gregLibert Sorry, as I'm not onboard the Massa team anymore, I got rid of all the setup to test this.
However using a simple Virtualbox VM, you can easily test if you are able to reproduce the bug using the instructions I left on the list.

**Comment by Thykof** [comment]
> (bonus issue) An icon is created for MassaStation, but when we click on it, it starts silently in the background (I had no idea what was happening)

This has been fix, launching massa station open the home page in the prefered browser

> When on WebUI, after installing the Wallet module, pressing "Launch" opens a 404 page
probably because the wallet in installed but crashes immediately because you might miss this lib: libwebkit2gtk-4.0-37. We are adding a note in the doc to document this dependency. cc @SlnPons

**Comment by Thykof** [comment]
closing in favor of https://github.com/massalabs/station-massa-wallet/issues/894
