### ISSUE TITLE
DNS mess up after deb installation

### ISSUE THREAD

**Issue by litchipi** [massalabs/station#1094]
**The problem(s)**
When installing the .deb, the installation script symlinks an external `resolv.conf` (from NetworkManager) to `/etc/resolv.conf`.
In some cases, the file `/etc/resolv.conf` of NetworkManager isn't available, the symlink points to nothing, and DNS services stops working.

**To Reproduce**
- Start a fresh Debian 12 VM
- Install the .deb package from the release (it should fail)
- Try to execute `ping www.google.fr`

**Expected behavior(s)**
Should handle the case where the external file doesn't exist yet

**MassaStation version**
Latest version

**Desktop (please complete the following information):**
- Debian 12 bookworm VM taken from [here](https://www.linuxvmimages.com/images/debian-12/)

**Comment by gregLibert** [comment]
This topic should be tackled when we rework the web-on-chain. @SlnPons , please feel free to tag this issue for easier reference and refinement in the future, or not 😁.
