### ISSUE TITLE
Request for Immediate Operation ID Retrieval on Smart Contract Calls

### ISSUE THREAD

**Issue by Ben-Rey** [massalabs/station#1097]
**Context**
When I initiate a smart contract call using the Massa Station wallet, I'd like to immediately receive the operation ID without waiting for the first event to be triggered. 
This immediate feedback would greatly enhance the user experience and provide clarity on the operation's status.

**User flow**
As a developer, after setting up a smart contract call and sending the request, I expect an immediate response from the the wallet so I can handle request like other wallets.

**How to**
- Update Swagger file to add `async` in `cmd/executeFunction` body
- Refacto `CallFunction` and `CallFunctionUnwaited` into a single `CallFunction` function that takes an `async: bool` parameter. If set to true, the function 
- Update `cmd/executeFunction` [handle](https://github.com/massalabs/station/blob/be6a2a5ce1d53b565028c4f0d531c65c40e95e63/int/api/cmd/execute_function.go#L24)
- Ensure to replace correctly every occurences of `CallFunction` and `CallFunctionUnwaited` (it shouldn't compile and you should have errors where you need to update things)
- Update Robot tests for `cmd/executeFunction`

<details>
<summary>Previous How To</summary>

several option:
- Create a call smart contract endpoint that returns the opId immediately (can be a way to name the endpoint 
- modify the current enpoint `cmd/executeFunction` to not return first event data (analysis of breaking change needed)

</details>

**Technical details**
the function that call smart contract and wait for the first event is here:https://github.com/massalabs/station/blob/2a4e8d8d178903baff88da1c10c312c496698e30/pkg/onchain/sc.go#L33

The function that call smart contract and return the operation ID is here:
https://github.com/massalabs/station/blob/2a4e8d8d178903baff88da1c10c312c496698e30/pkg/onchain/sc.go#L73

we just need to plug all function when we want to

**QA testing:**
- Install MassaStation
- Start MassaStation
- Try to upload a website
- (wait a few seconds after the upload finished since the front end isn't 100% accurate)
- Check if the website is working properly

You shouldn't have any errors here, everything is supposed to work

**Comment by Thykof** [comment]
To tackle this task we have several options:

Option 1:
The more straight forward: simply remove the first event from the response. This option is breaking.

Option 2:
Add a query parameter: `?event=first`: default and current behavior, `?event=no`: no event.

Option 3:
Add a new endpoint. 


I would prefer option 1

**Comment by peterjah** [comment]
i would vote for option 2, for backward compatibility and also to have both behaviour available.
My proposition for the parameter name is `?async=false` (default behaviour like current implem) 
 `?async=true` will return the opId without waiting inclusion in block

**Comment by Thykof** [comment]
I agree with your proposition @peterjah let's go!
