### ISSUE TITLE
add CA into macos OS store

### ISSUE THREAD

**Issue by Thykof** [massalabs/station#1098]
**Context**
*Describe / explain why we should do this: motivations, context or other info. Keep it brief and simple - PM*

Http navigation on Chrome on macos is currently not working because chrome on macos doesn't look into NSS store.

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*

**How to**
*List the step-by-step to get it do if needed - PM*

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by Thykof** [comment]
blocked: I don't find a way to add a certificate to the OS store without sudo

**Comment by longgamma-massa** [comment]
@Thykof I have the same issue with FF https. Should I add new issue or can be tackled with this one?

**Comment by Thykof** [comment]
> @Thykof I have the same issue with Firefox's https. Should I add new issue or can be tackled with this one?

let's investigate together and see how to tackle this.

**Comment by thomas-senechal** [comment]
I checked on my MacOS laptop, I can confirm that HTTPS isn't working on Chromium based Web Browsers. HTTPS is working well on Firefox, and HTTP is working on all Web Browsers

**Comment by longgamma-massa** [comment]
On my side:
- https not working on: FF, Chrome
- http not working on: Chrome
- 'add existing account' not working on FF, while 'create account' on wallet module does work
