### ISSUE TITLE
Installation fails on Windows 11

### ISSUE THREAD

**Issue by Leo-Besancon** [massalabs/station#1102]
I'm trying to install MassaStation [(v0.3.0)](https://github.com/massalabs/station/releases/tag/v0.3.0) on my Windows 11, and I have the following error:
```
PS C:\Users\leole\Desktop> .\massastation_windows_amd64.exe
2023/08/16 22:09:04 while initializing logger: initialize global logger:
open log file: open C:\Users\leole\Desktop\logs\massastation.log:
The system cannot find the path specified.
```

**Comment by Leo-Besancon** [comment]
Oh, I was trying to launch the .exe instead of the .msi.
It works now.

**Comment by thomas-senechal** [comment]
Closing following https://github.com/massalabs/station/issues/1102#issuecomment-1681215338
