### ISSUE TITLE
Firefox does not trust CAs in the Windows Certificate Store by default.

### ISSUE THREAD

**Issue by Leo-Besancon** [massalabs/station#1111]
I encountered this issue because massa wallet provider has a CORS error on my Firefox when querying massa station, although it works on Chrome.

It lead me to this thread: https://stackoverflow.com/questions/24514666/why-is-this-cors-request-failing-only-in-firefox/68411349#68411349
TL;DR: Firefox does not trust the CAs in the Windows Certificate Store by default, and therefore does not trust MassaStation. This may lead to a lot of issues for our users.

By setting `security.enterprise_roots.enabled` to `true`, the problem was resolved. But I'm not sure if we want to edit firefox's config on Massastation's install.

**Comment by thomas-senechal** [comment]
Hi @Leo-Besancon 
Could you retry with [v0.3.1](https://github.com/massalabs/station/releases/tag/v0.3.1) ? 
It was released yesterday and should fix this issue

**Comment by Leo-Besancon** [comment]
Yes, it works without the config edit now, thanks ;)
