### ISSUE TITLE
Web onchain upload expects me to know regex 

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/station#1113]
**The problem(s)**
when trying to upload a website on the web on chain with a unsupported name i get an error message with the expected format in regex

**To Reproduce**
upload a website with the name "LKLA akJKAI" for exemple 

**Expected behavior(s)**
Show me a user friendly error message

**Screenshots**
<img width="420" alt="Screenshot 2023-08-22 at 16 28 14" src="https://github.com/massalabs/station/assets/90157528/a4d331a4-260a-4a74-8f83-24483136db29">

**MassaStation version**
MassaStation v0.3.1

**Comment by longgamma-massa** [comment]
Proper message:
The website's name can only consist of lowercase letters, numbers, and the characters _.-~, and must be between 3 and 50 characters in length.

@LucasF243 can you check in designs if the message is too long?

**Comment by pivilartisant** [comment]
there is a slight displacement : https://github.com/massalabs/station/pull/1114 see description 
--> @longgamma-massa  from a product point of view wdyt ?

**Comment by Thykof** [comment]
I tested by manually enabling in the code the upload feature. It work fine, like the provided screenshot

**Comment by longgamma-massa** [comment]
can you share screenshot here please?

**Comment by Thykof** [comment]
yes, screenshot is here: https://github.com/massalabs/station/pull/1114#issue-1861745120
