### ISSUE TITLE
WebOnChain is broken for multiple chunks websites

### ISSUE THREAD

**Issue by peterjah** [massalabs/station#1120]
**The problem(s)**
Unable to browse large websites. (zip.file size > 1 chunk = 260kb)

**To Reproduce**
Upload tictactoe.zip, and try to browse it

Station logs shows:
```
ERROR	logger/global.go:106	handling massa domain request: fetching the 'index.html' web resource at 'AS12nL2ofM84z5u8426PmQsURcvmTg5XymC64kToZvh19NXcNavyT': fetching the 'index.html' web resource at 'AS12nL2ofM84z5u8426PmQsURcvmTg5XymC64kToZvh19NXcNavyT': fetching website content at AS12nL2ofM84z5u8426PmQsURcvmTg5XymC64kToZvh19NXcNavyT from blockchain: invalid chunk size for chunk 0
```

So there is a bug either in the upload process, or in the browse implem!

 **Any other useful info**
[tic-tac-toe.zip](https://github.com/massalabs/station/files/12429092/tic-tac-toe.zip)

**Comment by thomas-senechal** [comment]
I can confirm the issue.
I checked and it was also the case on [v0.3.0](https://github.com/massalabs/station/releases/tag/v0.3.0)

We clearly need to add some tests with big websites once this is fixed.

**Comment by Thykof** [comment]
QA: I tested by manually enable upload feature, I uploaded a labby which is more than one chunk, it works well: https://labynathan18.massa

**Comment by longgamma-massa** [comment]
it is enough to close @Thykof ? Do we need another check with different example?
