### ISSUE TITLE
Auto open `https://station.massa` at launch

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/station#1124]
**Context**
When I launch massa station, nothing happens, I have to remember that I should go to my browser and open It.

**User flow**
Launch massa station and auto open the UI in the default browser Or show a message 

We could also add It to tool barre, It's the best way for this long running processes:

![image](https://github.com/massalabs/station/assets/22281426/70708517-ba82-48f1-b852-6384af4b8ede)

So I have to click and we'll have : Open, Restart, Quit etc

**Comment by thomas-senechal** [comment]
Closing as done ! https://github.com/massalabs/station/issues/1015
