### ISSUE TITLE
Delete uploaded websites 

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/station#1128]
**Context**
Ability to remove a website uploaded on-chain. 

**User flow**
- Select website to delete from 'My websites'
- Understand the process of deleting the website:
a. What will be erased (how many chunks), 
b. What I need to sign (which operation) 
c. How much it will cost me (transaction cost)
d. Storage renting returns -> How much MAS I am getting back for freeing up the disk space.
- See the signature pop up. 
- Approve the operation.
- See status of operation. 
- See Website removed from My websites. See MAS returned for storage space.

**How to**
- Designs and frontend needed
- Backend related issue https://github.com/massalabs/station/issues/1139

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by gregLibert** [comment]
This topic should be tackled when we rework the web-on-chain. @SlnPons , please feel free to tag this issue for easier reference and refinement in the future, or not 😁.
