### ISSUE TITLE
refactor DecodeOperationType and create an enum with the different operation types

### ISSUE THREAD

**Issue by B-Naoufal** [massalabs/station#1131]
**Context**
<img width="811" alt="image" src="https://github.com/massalabs/station/assets/16125633/50ac341f-eb82-41d6-8357-90bbc1f839da">

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*

**How to**
*List the step-by-step to get it do if needed - PM*

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by thomas-senechal** [comment]
https://github.com/massalabs/station-massa-wallet/pull/652#discussion_r1307360276

**Comment by Thykof** [comment]
that's true, the operation id is something else, described here: https://docs.massa.net/docs/learn/operation-format-execution#operation-id
