### ISSUE TITLE
Add missing websites features

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/station#1136]
**Context**
In the previous Station UI, it was possible to:
- List all websites
- List websites you own
- Upload a website
- Edit a website
- Upload missing chunks of a website

The new (and current) UI only supports listing all websites and uploading a website. We want to bring back the other features

**User flow**
- User uploads a website
- The website is added the the list of websites they uploaded

- User clicks on a button to edit a website
- Selects the zip file to upload
- The website is updated

- In the list of websites user uploaded, there is an icon if a website has missing chunks
- The user can click on it to send the zip file again
- The missing chunks are reuploaded and the website works again

**How to**
For each feature:

- [ ] Create the issue
- [ ] Design the frontend
- [ ] Implement the design in the frontend

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by thomas-senechal** [comment]
Note:

We also need to fix the website upload in the front end. The previous version showed a stepper in 1 steps:
- Deploy the SC
- Init the website (set the name and nbr of chunks)
- Upload chunks (with a counter such as "Uploading chunks 1/4...")

It would be great to at least take this into account while designing the feature mentionned in this issue description

**Comment by gregLibert** [comment]
This issue should be addressed during the web-on-chain rework. @SlnPons, please let me know if you think my cleanup was excessive.
