### ISSUE TITLE
Remove website from blockchain storage when DNS entry is removed.

### ISSUE THREAD

**Issue by B-Naoufal** [massalabs/station#1139]
**Context**
*Today when we remove a website from web on chain, we only remove the entry from the DNS, but the zip file is never removed from the blockchain*

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*

**How to**
*List the step-by-step to get it do if needed - PM*

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by longgamma-massa** [comment]
@gregLibert correct me here, but this is up to the user to remove to free up the space. Maybe we need a feature in the wallet to allow them to do so?

**Comment by gregLibert** [comment]
> @gregLibert correct me here, but this is up to the user to remove to free up the space. Maybe we need a feature in the wallet to allow them to do so?

It is up to the user to free the space. But the possibility to remove the website at the SC level was missing. But I think now this done.

@peterjah can you confirm that ?

**Comment by peterjah** [comment]
> > @gregLibert correct me here, but this is up to the user to remove to free up the space. Maybe we need a feature in the wallet to allow them to do so?
> 
> It is up to the user to free the space. But the possibility to remove the website at the SC level was missing. But I think now this done.
> 
> @peterjah can you confirm that ?

The new websiteManager contract allow to delete uploaded chunks. But this is still not implemented in MAS

**Comment by longgamma-massa** [comment]
@LucasF243 here we need the flow. Users who upload websites should be able to remove the chunks and free up the storage space.

**Comment by gregLibert** [comment]
This issue should be addressed during the web-on-chain rework. @SlnPons, please let me know if you think my cleanup was excessive.
