### ISSUE TITLE
Remove "buildnet/index" from website URL, when fetching websites from the web onChain.

### ISSUE THREAD

**Issue by B-Naoufal** [massalabs/station#1140]
**Context**
*![image](https://github.com/massalabs/station/assets/16125633/b66258a7-baea-4e20-9f7a-89149efeba64)*

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*

**How to**
*List the step-by-step to get it do if needed - PM*

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by gregLibert** [comment]
This topic should be tackled when we rework the web-on-chain. @SlnPons , please feel free to tag this issue for easier reference and refinement in the future, or not 😁.
