### ISSUE TITLE
Cannot send empty string as params for a callSc

### ISSUE THREAD

**Issue by Ben-Rey** [massalabs/station#1144]
**The problem(s)**

When we try to send a smart contract call operation to massation with no Args we get an error

```text 
"message": "Error: callSC failed: calling function 'test' at 'AS12VWmiiVmpLCdAiUrMRGMEat3swV4jiTGihKdX647uSCoJkWaUx' with '[]': signing operation: calling executeHTTPRequest for call: request failed with status: 400 Bad Request, message: Error: Wallet-0012"
```

**To Reproduce**

Using wallet provider:
```typescript
   if (!client) return;

    try {
      setLoading(true);
      const result = await client.smartContracts().callSmartContract({
        fee: BigInt(1000),
        maxGas: BigInt(1000000),
        coins: BigInt(0),
        targetAddress: CONTRACT_ADDRESS,
        functionName: "test",
        parameter: new Args(),
      });

      console.log(result);

      const eventPoll = await pollAsyncEvents(client, result);

      alert(`New event: ${eventPoll.events[0].data}`);
      setLoading(false);
    } catch (error) {}
```

**Expected behavior(s)**

We should be able to send a callSc operation with no Args

**Screenshots**

**MassaStation version**
The version of MassaStation the bug is present in.

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows...]
 
 **Any other useful info**
 The error on massa station side (Go)
`[wallet-plugin] Error: failed to decode callSC message: failed to read parameters: EOF`

**Comment by thomas-senechal** [comment]
This bug has been fixed in #1145 
To make it available, we still need to (in this order):

- [ ] Release Massa Station
- [ ] Update the dependency to station in the wallet (and fix the issues as explained in [this comment](https://github.com/massalabs/station/pull/1145#issuecomment-1704816243))
- [ ] Release Massa Wallet

**Comment by thomas-senechal** [comment]
Not done as explained in my previous comment

**Comment by thomas-senechal** [comment]
Wallet release is expected this friday

**Comment by thomas-senechal** [comment]
I'm closing this issue since the fix has been released (nearly 2 weeks ago 😅)
