### ISSUE TITLE
Plugin Installation is failing due to 403 error from Github

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/station#1150]
**The problem(s)**
When installing a plugin, we download it's archive from github releases. But right now, MassaStation is unable to download plugins from Github due to 403 Forbidden error

**To Reproduce**

**Expected behavior(s)**

**Screenshots**

**MassaStation version**
[Latest main](https://github.com/massalabs/station/tree/852f45c6fe892dac56b7fe43c71d150275c4363b) and previous versions of MassaStation (v.0.3.2, v0.3.1)

**Desktop (please complete the following information):**
 - OS: MacOS and Windows for sure, very likely on Linux (not tested yet)
 
 **Any other useful info**

**Comment by thomas-senechal** [comment]
This might be related to some changes on Github API side, especially to avoid scrappers.

We are attempting to set a custom User Agent to see if it allows us to download plugins.

**Comment by longgamma-massa** [comment]
How to q/a?

**Comment by thomas-senechal** [comment]
> How to q/a?

1. Install MassaStation
2. Attempt to install a plugin
3. The plugin should be installed 

If the plugin does not install, please open your web browser dev tools and retry to install.
Check if there is an error in the network part. If so, check what is the error message.
If it's something related to "couldn't download ... 403 Forbidden", that means that there are still issues in some cases
If it's another error, please send it here so we can see if it's related to this issue or not
