### ISSUE TITLE
User must agree on T&C before install

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/station#1156]
**Context**
User must click on ‘agree to ToC’ before downloading Station.  
From legal team: "you have to propose the T&Cs at the moment the user clicks on the download button, so before the installation process as such"

**How to**
Add the ToC in the installer on all OSs.

1. Windows users: can see the T&Cs in a doc version during the installation.
2. MacOS users: have a dedicated section in the installer where user can read, and accept them.
3. Linux: ?

[T&C in PDF](https://www.notion.so/massa-innoteam/Agree-on-Terms-and-Conditions-in-the-installation-flow-e2fe4322ab8843f7946e54d144d28286?pvs=4) 

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by LucasF243** [comment]
The T&C should be added to the station installer, so as not to damage the flow, and to find a solution for Github

@mazmassa WDYT ?

**Comment by mazmassa** [comment]
I agree with @LucasF243 .
Everybody should be able to download it. However, to go further with the installation we should propose the ToC to be approved first.

**Comment by thomas-senechal** [comment]
Reopening, Only done for Windows

**Comment by longgamma-massa** [comment]
@thomas-senechal Just confirm it has been tested on all OS before merging? On MacOS it works as intended

**Comment by thomas-senechal** [comment]
> @thomas-senechal Just confirm it has been tested on all OS before merging? On MacOS it works as intended

Yes, we tested it on all OS's before merging each PR
