### ISSUE TITLE
Can't install station 0.3.4 on MacOS 13.5.2

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/station#1166]
**The problem(s)**

The installation of station fails on the latest macos version (13.5.2)

**To Reproduce**

Try to install the ARM64 PKG of station version 0.3.4

**Expected behavior(s)**

Working.

**Screenshots**

Logs of the installer
[message (8).txt](https://github.com/massalabs/station/files/12606844/message.8.txt)

**MassaStation version**
0.3.4

**Desktop (please complete the following information):**
 - OS: MACOS 13.5.2
 
 **Any other useful info**

`brew install nss` manually on my terminal worked great but doesn't solve the problem.

Contact me on discord if you want me to test something to find the bug

**Comment by thomas-senechal** [comment]
Installation works fine on my laptop with MacOS 13.4.1

**Comment by thomas-senechal** [comment]
From @longgamma-massa : Works on MacOS Monterrey 12.6

**Comment by AurelienFT** [comment]
Just added the logs of hte installer in the issue totally forgot to do it before, sorry

**Comment by longgamma-massa** [comment]
I just updated to Ventura 13.5.2 and had a successful installation of arm64 pkg @thomas-senechal

**Comment by thomas-senechal** [comment]
> I just updated to Ventura 13.5.2 and had a successful installation of arm64 pkg @thomas-senechal

Same, updated to 13.5.2 and no issue

**Comment by gregLibert** [comment]
> **The problem(s)**
> 
> The installation of station fails on the latest macos version (13.5.2)
> 
> **To Reproduce**
> 
> Try to install the ARM64 PKG of station version 0.3.4
> 
> **Expected behavior(s)**
> 
> Working.
> 
> **Screenshots**
> 
> Logs of the installer [message (8).txt](https://github.com/massalabs/station/files/12606844/message.8.txt)
> 
> **MassaStation version** 0.3.4
> 
> **Desktop (please complete the following information):**
> 
> * OS: MACOS 13.5.2
> 
> **Any other useful info**
> 
> `brew install nss` manually on my terminal worked great but doesn't solve the problem.
> 
> Contact me on discord if you want me to test something to find the bug

Extracted error:
```
Sep 14 10:04:46 Aureliens-MacBook-Pro package_script_service[6855]: ./postinstall: Error: Cannot install in Homebrew on ARM processor in Intel default prefix (/usr/local)!
Sep 14 10:04:46 Aureliens-MacBook-Pro package_script_service[6855]: ./postinstall: Please create a new installation in /opt/homebrew using one of the
Sep 14 10:04:46 Aureliens-MacBook-Pro package_script_service[6855]: ./postinstall: "Alternative Installs" from:
Sep 14 10:04:46 Aureliens-MacBook-Pro package_script_service[6855]: ./postinstall:   https://docs.brew.sh/Installation
Sep 14 10:04:46 Aureliens-MacBook-Pro package_script_service[6855]: ./postinstall: You can migrate your previously installed formula list with:
Sep 14 10:04:46 Aureliens-MacBook-Pro package_script_service[6855]: ./postinstall:   brew bundle dump
Sep 14 10:04:46 Aureliens-MacBook-Pro package_script_service[6855]: ./postinstall: FATAL: failed to install nss using homebrew
```
