### ISSUE TITLE
display plugins version

### ISSUE THREAD

**Issue by peterjah** [massalabs/station#1167]
**Context**
Display plugins version.
The plugin versions is already available from the API
To discuss with designer for the integration

**QA testing**
See version displayed

**Comment by longgamma-massa** [comment]
@LucasF243 can you share/do designs for this one?

**Comment by LucasF243** [comment]
https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=6326%3A41681&mode=design&t=4DRlcvECH1rbjh24-1

**Comment by Thykof** [comment]
QA: works well, but version should be vX.Y.Z, not v.X.Y.Z (period too many)

**Comment by Thykof** [comment]
I have opened a PR here https://github.com/massalabs/station/pull/1184
