### ISSUE TITLE
Display MassaStation version

### ISSUE THREAD

**Issue by peterjah** [massalabs/station#1168]
**Context**
Display MassaStation version in the Station's UI.
We will add the version next to Massa Station's logo (check comment below for designs).

**QA testing**
See version displayed

**Comment by longgamma-massa** [comment]
@LucasF243 propose a few options for the version display of Station

**Comment by LucasF243** [comment]
there is already this solution to display the version: https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=2551%3A19989&mode=design&t=43OfoxqhPfeQmSxo-1

**Comment by pivilartisant** [comment]
this was addressed here : https://github.com/massalabs/station/pull/1182

**Comment by pivilartisant** [comment]
Reopening to track frontend

**Comment by longgamma-massa** [comment]
@pivilartisant While Q/A-ing from Main branch, everything was okay.

After we made an official release I see 2 vv's.


Tested on: MacOS arm (M1)

**Comment by pivilartisant** [comment]
https://github.com/massalabs/station/pull/1228

**Comment by pivilartisant** [comment]
This is bizarre because back end does not add a "v" and the front end only appends one "v" to the version number
