### ISSUE TITLE
Can't update wallet to v.0.2.6 on station 0.3.4

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/station#1175]
**The problem(s)**
Can't update wallet to v.0.2.6 on station 0.3.4

**To Reproduce**
Go to https://station.massa/web/store and don't have a yellow button to update

**Expected behavior(s)**
Having the button

**Screenshots**
<img width="781" alt="Screenshot 2023-09-19 at 10 18 31" src="https://github.com/massalabs/station/assets/32803821/12fc78dc-9fcc-45f2-8946-b330f1488403">

**MassaStation version**
0.3.4

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows...] MacOS 13.5.2 (M1)
 
 **Any other useful info**

**Comment by pivilartisant** [comment]
These are the current version of wallet plugin and MS :
```
❯ cat /usr/local/share/massastation/plugins/wallet-plugin/manifest.json | grep version

  "version": "0.2.5",
```

```
❯ /Applications/MassaStation.app/Contents/MacOS/massastation -version

Version:v0.3.4
```

**Comment by longgamma-massa** [comment]
@AurelienFT Can you check if we solved your issue? 
How-to:

1. Download Station from Artifacts for your MacOS [from here](https://github.com/massalabs/station/actions/runs/6236980872)
2. Install Wallet module's version v0.2.5, by pasting this link in the 'upload module' panel: https://github.com/massalabs/station-massa-wallet/releases/download/v0.2.5/wallet-plugin_darwin-arm64.zip
3. See if you get the update (orange) button and can update to v0.2.6 of Massa wallet successfully.

**Comment by AurelienFT** [comment]
> 2\. Install Wallet module's version v0.2.5, by pasting this link in the 'upload module' panel: https://github.com/massalabs/station-massa-wallet/releases/download/v0.2.5/wallet-plugin_darwin-arm64.zip

Gives me this error : 
```
"Error: downloading plugin at https://github.com/massalabs/station-massa-wallet/releases/download/v0.2.5/wallet-plugin_darwin-arm64.zip: renaming plugin wallet-plugin: creating the plugin .app directory at /usr/local/share/massastation/plugins/wallet-plugin/wallet-plugin.app: mkdir /usr/local/share/massastation/plugins/wallet-plugin/wallet-plugin.app: file exists"
```

**Comment by AurelienFT** [comment]
Only by reinstalling massa station and close it and re-open it I have the orange arrows

**Comment by Thykof** [comment]
Great, so can we close this issue?
