### ISSUE TITLE
Add Ubuntu Update GUI Specific Doc Instructions

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/station#1186]
**Context**
The graphic user interface for ubuntu (software install) does not detect version changes in programs so it is expected that when updating, the user can’t go through the same flow as described here : https://github.com/massalabs/station/blob/main/INSTALLATION.md#debian-linux-installation 

**User flow**
In order to improve the UX for ubuntu users who decide to use the GUI we must : 

**How to**
1) Change the order of install documentation so user aren't enclined to use GUI -> first “Terminal Installation using apt” than “GUI Installation” 
2) Adding a paragraph in the GUI section specific to updating flow warning users that the GUI will not work and it is preferable to use the command line. But is they want to use the graphic interface they will need to follow these https://github.com/massalabs/station/blob/main/INSTALLATION.md#linux instructions first 

**Technical details**
This will be done here : https://docs.massa.net/docs/massaStation/home#installation
And here : https://github.com/massalabs/station/blob/main/INSTALLATION.md#debian-linux-installation

**Comment by pivilartisant** [comment]
Objective is to clarify situations like this: https://github.com/massalabs/station/issues/1171

**Comment by Thykof** [comment]
@longgamma-massa the documentation is duplicated on the docs repo and station repo. This is a warning for maintainability of this documentation. Should we consider reorganize our documentation station repo (for instance put link to https://docs.massa.net)?

**Comment by longgamma-massa** [comment]
good idea. there's some reorganization to do. Addressing in the follow up issue.
