### ISSUE TITLE
Improve 'Upload website' 

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/station#1209]
**Context**
Following up discussion and need here: https://github.com/massalabs/station-massa-wallet/issues/671
We decided to keep the batch operations and give user more visibility on the costs and errors that can occur during uploading website on-chain. 

**Need:**
**Show total costs:**
 - Inform user on the 'transaction cost'.
 In Massa, the overall transaction cost is `fee + coins` where `fee` is the compensation paid to the validators for computational work and `coins` is the amount of coins locked for storage space on the ledger. 
 - On user action to know more (it can be a drop-down for example), display "Coins" and "Fees" with tooltips explaining each.
 @LucasF243 update design flow to match this: https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=6365-27176&mode=design&t=Hp8cwqcX4eQ0YcTj-0

**Show error about occupied domain name:**
- Check for 'Domain name taken' before signing the operation batch. 
This way user doesn't lose the funds for the first operation if the second one will fail because of this error: https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=6365-27290&mode=design&t=Hp8cwqcX4eQ0YcTj-0

**Improve 'sign' wails pop up for batch operations:**
- Users must know they are signing a batch of operations, and if interested, they can get the details in 'description field' that will be provided from backend.

**Comment by gregLibert** [comment]
This topic should be tackled when we rework the web-on-chain. @SlnPons , please feel free to tag this issue for easier reference and refinement in the future, or not 😁.
