### ISSUE TITLE
Massa Station shuts down internet access on Windows

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/station#1210]
**Context**
During the installation in some Windows cases, due to changes in DNS settings Station shuts down the internet. In this case user can't troubleshoot as he has no internet, he pretty much can't do anything. 

**User flow**
can't reproduce it easily, we don't know the source. It's **an edge-case but a big user pain.**

**How to**
- [ ] Expected behaviour for this case is to show the user an error message at this installation step that: 
A) OS encountered a problem during Station's installation. 
B) User must restart his PC.
The message can be improved based on other information we find about this issue.

**Technical details**

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by longgamma-massa** [comment]
@gregLibert @thomas-senechal with the DNS task we implemented, do we still need this issue?

**Comment by gregLibert** [comment]
Should not be a problem anymore as we are not changing network interface anymore in the last version.
