### ISSUE TITLE
Detect and inform on unsupported OS during installation

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/station#1211]
**Context**
Users who download OS versions that we don't support Massa Station for, should be informed immediately on installation about it. There's no need for these users to continue downloading. 

**User flow**
1. Clicked on 'download' from landing page
2. Downloaded package
3. Started installation process
4. Failed to install on unsupported OS version on Windows, MacOS, Linux

**How to**
If unsupported OS version on  show: 
"Oops! Massa Station cannot be installed on your current [OS] version ([version name/no.]).
We require [version name/no] or a newer version for compatibility. Please consider updating your operating system to enjoy Massa Station."

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by thomas-senechal** [comment]
Should be easy
https://wixtoolset.org/docs/v3/howtos/redistributables_and_install_checks/block_install_on_os/

**Comment by thomas-senechal** [comment]
https://fr.wikipedia.org/wiki/Windows_NT
