### ISSUE TITLE
Add 'Manual installation guides

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/station#1215]
**Context**
Adding a "manual installation guide" would be great for people with specific configurations such as: VPN, a DNS already installed, and others who don't want us to change their settings during installation. 
- We can also use it to instruct frustrated users who don't want to allow Massa Station to change their OS config.

**User flow**
1. User comes to landing page
2. User is directed to Massa Docs
3. User can see Manual installation guides

**How to**
- In Massa Docs, have a section in "Installation".
- In Installation section, have a linkable subsection "Manual installation" 
- Add this new guide to the FAQ on Discord and tech-ambassador guides

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by thomas-senechal** [comment]
Closing as it's done https://docs.massa.net/docs/massaStation/manual-install
