### ISSUE TITLE
Windows installer logs corrupt due to encoding incompatibilities

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/station#1218]
**The problem(s)**
On Windows, logs of the `configure_acrylic.bat` script are partly corrupt. For example, for Russian language windows, the logs of this script contains mostly asian characters. Even with a French Windows, the file is readable but partly corrupt

**To Reproduce**
- Install MassaStation
- Check logs in `%TEMP%`
- See weird characters

**Expected behavior(s)**
- The logs shouldn't be corrupted 

**Screenshots**
![image](https://github.com/massalabs/station/assets/44696378/d3e00550-55de-4487-b4cd-f1373c8ac290)

**MassaStation version**
v0.3.5

**Desktop:**
 - OS: Windows
 
 **Any other useful info**
- Looks like the issue is here because of using Powershell to run  `configure_acrylic.bat`, but having the log file generated by cmd, and so, the file is encoded in ANSI while powershell uses another encoder such as UTF-8.

**Comment by thomas-senechal** [comment]
**QA testing:**

- Download for Windows from https://github.com/massalabs/station/actions/runs/6468857290?pr=1226
- Install it using the "complete" option
- Go to your file explorer
- Type `%TEMP%` in the top bar
- Sort to have latest modified first
- Check for the log file named `MASSASTATION_INSTALLER_0.3.6.log`
- Open it with notepad
- Check for the used encoding (should be the weird value at the bottom right). Should be something like `UTF-16...` (might difer  depending on your Windows language and version, ping me if necessary)

**Comment by Thykof** [comment]
I tested, it works

**Comment by LucasF243** [comment]
works for me too
