### ISSUE TITLE
Fix .msi installer file name

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/station#1227]
**Context**
After signing Windows code, we experienced an issue with showing proper **.msi** filename. 

**User flow**
1. User must click to allow app to install in the dialogue window.
User should see a proper file name displayed, like it was before code-signing. At the moment it looks strange, especially combined with 'terminals opening' #984 

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
- Download MS
- Start the installer
- At the moment you are asked to give admin access, check the name of the thing you are giving access to:
  - It should be "Massa Station"

**Comment by thomas-senechal** [comment]
Looking at the [doc](https://ebourg.github.io/jsign/), it should be easy to fix using the `-name` argument
