### ISSUE TITLE
Massa station does not start: port 80 access forbidden

### ISSUE THREAD

**Issue by aydarM** [massalabs/station#1250]
**The problem(s)**
Massa station does not start

**To Reproduce**

**Expected behavior(s)**

**Screenshots**

![изображение](https://github.com/massalabs/station/assets/104096453/780965ea-f8d0-4d52-aeca-542d289aa549)

**MassaStation version**
massastation_0.3.8_amd64

**Desktop (please complete the following information):**
Windows
 
 **Any other useful info**

**Comment by gregLibert** [comment]
No response from user. I'm closing
