### ISSUE TITLE
Issue MacOs

### ISSUE THREAD

**Issue by alexp799** [massalabs/station#1277]
[Installer Log 25-Nov-2023.txt](https://github.com/massalabs/station/files/13462575/Installer.Log.25-Nov-2023.txt)
**The problem(s)**

**To Reproduce**

**Expected behavior(s)**

**Screenshots**

**MassaStation version**
The version of MassaStation the bug is present in.

**Desktop (please complete the following information):**
MacOs
 **Any other useful info**

**Comment by thomas-senechal** [comment]
Hi @alexp799 
It looks like the error is coming from an attempt to install xcode that was never completed:
```
Error: You have not agreed to the Xcode license. Please resolve this by running:
  sudo xcodebuild -license accept
```

Could you please open a terminal and run the following command:
```
sudo xcodebuild -license accept
```
