### ISSUE TITLE
Have an rpm package

### ISSUE THREAD

**Issue by XavSPM** [massalabs/station#1278]
Have other package formats other than .deb. This would allow more people to use massastation. 

This doesn't require much development time. All you have to do is define the dependencies to be used and modify the installation scripts to incorporate them into the rpm package. The binary already works on Fedora.

**Comment by Thykof** [comment]
Hi @XavSPM 

Thank you for expressing interest in having an RPM package for Fedora. Currently, it's not on our immediate roadmap, but we appreciate your suggestion. We encourage community contributions, and if you're interested, we'd love to see a pull request from you. Feel free to contribute and help make it happen!
