### ISSUE TITLE
Installed plugin still appearing in "store" list

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#1305]
**The problem(s)**
After installing the wallet plugin, it still appears in the store list whereas it should appear in the installed list.

**To Reproduce**
Try to install the wallet and go to the store page

**Expected behavior(s)**
As soon as a plugin is installed, it should be displayed in the "installed" list of plugins

**Screenshots**

**MassaStation version**
v0.5.0

**Desktop (please complete the following information):**
 - OS: MacOS
 
 **Any other useful info**

**Comment by Thykof** [comment]
now it works
