### ISSUE TITLE
In thyra app, step 1 is active (with ...) while the prompt is open

### ISSUE THREAD

**Issue by Thykof** [massalabs/station#192]
# Step to reproduce
In the website page, fill and submit the form. You see the stepper:
![image](https://user-images.githubusercontent.com/11590067/196168486-d174732d-bc26-4dd7-b830-eae89fcc2b6f.png)

You see that step 1 is active.
You see also the password prompt of the GUI.

## Problem
Step one has not really started because you have not entered your password yet, but you see the step one active.

# Expected behavior
 No action should start before the user type and validate their password.
The upload module shouldn't change until the user clicks on 'OK' in the prompt + the password is correct.
In other terms, the user journey is: 
End user adds all info to upload a website
End user click on 'deploy to massa' button 
End user sees the prompt and type in their password (the upload module state should stay the same at this moment but all fields should be in read only to prevent user from changing info)
End user clicks on 'OK' to submit the password 
If password is ok, then the upload module should starts

**Comment by Thykof** [comment]
@SlnPons I have update the description

**Comment by thomas-senechal** [comment]
This is mainly a visual issue that isn't affecting the proper functioning of Thyra. To fix it, we could use websockets between the API and the front-end to let the front-end know when the password has been entered. But since it's just a visual issue, it has been decided to not fix this bug right now to focus on priorities.

**Comment by Thykof** [comment]
This issue is deprecated. @SlnPons this is the only issue in milestone, but I don't think we should close this milestone however. should we list the issues related to webonchain?
