### ISSUE TITLE
Isolate Event Manager object

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#259]
**Context**
Thyra pluggenisation. See milestone description for more info about this product strategy.
DEFINITION:
An object will be defined as a set of attributes and methods associated to these attributes.

An attribute is defined as a property of an object (ex. the number of doors of a car is an attribute of a car model)
A method is defined as a standard way to achieve a specific functionality (ex. listening to music is a feature of a car that can be activated by using the method “turning on the radio”.)

**Needs**
* As a dev, I want the wallet functions and services to exist outside Thyra but still the event manager should work as today.

**How to**
- [ ] Externalise the event manager object

**Technical details**
To be added

**Comment by thomas-senechal** [comment]
List of issues that should be solved by this issue:

- https://github.com/massalabs/thyra/issues/192

**Comment by Thykof** [comment]
this issue is outdated
