### ISSUE TITLE
Thyra installation on Linux Manjaro - Archlinux

### ISSUE THREAD

**Issue by ASAPSegfault** [massalabs/station#275]
When trying to set up DNSmasq with the following command :

sudo cp /etc/NetworkManager/NetworkManager.conf /etc/NetworkManager/NetworkManager.conf_backup_thyra_install && sudo sed -i "s/keyfile/keyfile\ndns=dnsmasq/g" /etc/NetworkManager/NetworkManager.conf

It breaks the network manager service that cannot get restarted anymore, preventing Thyra itself from working.

**Comment by SlnPons** [comment]
ack, thanks Hugo :) 
This is "expected" in the sense of we only handle linux Ubuntu for now. But super important to report this as the more we'll have the need to use other config the more I'll prioritise it.
Another action based on this ticket will be to update the doc to make sure it's super visible which version we're handling or not! I'm on it.

**Comment by gregLibert** [comment]
I'm closing this issue for the time being:

- The distribution in question isn't on our list of supported distributions.
- DNS has been removed, so it's likely that the problem has been resolved in the latest version.

If the issue persists, please let us know, and we'll consider whether to expand our target distributions to include this one.

**Comment by SlnPons** [comment]
Find out all the info and guidelines about Massa Station's installation process [here](https://docs.massa.net/docs/massaStation/install)
