### ISSUE TITLE
Change encoding logic for the file size

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#278]
**Context** 
The way we handle the upload of a file on the Blockchain today is not good enough to satisfy coming needs which are the speed of upload and the fees management of large files. 
This is why we'll try to update some parts of our logic so that we can make sure that better manage these points to increase user satisfaction and product usability. 
Full context and details here: https://github.com/massalabs/thyra/issues/220 

**Needs** 
* As a PM, I want that the file uploaded by the user on Thyra to be encoded in 123 string instead of 64 like today so that it will increase the speed of upload and decrease the fees. 
* As a PM, I want to know the speed of upload and associated fees before the change described in this ticket and after so that I can compare and asses the results. 

**How to** 
- [ ] Measure the upload time and fees of the current logic 
- [ ] Update the encoding from 64 to 123 bytes
- [ ] Measure the upload time and fees with the new encoding system
- [ ] Share results with PM 

**Technical details**
To be added by the dev

**Comment by thomas-senechal** [comment]
It looks like this issue isn't up to date. 

Base64 isn't used anymore since https://github.com/massalabs/thyra/pull/330 . 

@SlnPons, I'm not sure we need this issue anymore.

**Comment by SlnPons** [comment]
@thomas-senechal what is the base used atm? 
Because the uploading is stil VERY slow compared to Massa blockchain block creation time period (2sec) .... 

We must be able to do sth about these logics (encoding and/or chunk upload) to improve this point for Massa web on-chain.

**Comment by gregLibert** [comment]
This topic should be tackled when we rework the web-on-chain. @SlnPons , please feel free to tag this issue for easier reference and refinement in the future, or not 😁.
