### ISSUE TITLE
Update chunk upload logic

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#281]
**Context**
The way we handle the upload of a file on the Blockchain today is not good enough to satisfy coming needs which are the speed of upload and the fees management of large files.
This is why we'll try to update some parts of our logic so that we can make sure that better manage these points to increase user satisfaction and product usability.
Full context and details here: https://github.com/massalabs/thyra/issues/220

**Needs** 
* As a Dev, I want to send the chunks by batch of X to the nodes so that each time a node validates one chunk I can immediately send another chunk straight away so that I don't have to wait for the chunks to be validated one by one or to get problems with the expiry dates as the expiry date. 

**How to**

- [ ] Create a tool / sth to measure the current time to upload a website in order to be able to compare and improve the speed
- [ ] Define the number of chunks to be sent at the same time to the network based on the upload speed and the cost. X=5 has been discussed during the meeting all together. Please define X and give context about why (arbitrary is a good enough explanation)
- [ ] Define the expiry period you put on every chunk sent to the network. Explain why you put that. (Not to be challenged, simply so we can come back to it later and potentially reword if needed)
- [ ] Update the current logic to batch logic described above 
- [ ] Test the full process to validate it works

**Technical details**
To be added by the dev

**Comment by gregLibert** [comment]
I have been a victim of this bug.

**Comment by gregLibert** [comment]
This topic should be tackled when we rework the web-on-chain. @SlnPons , please feel free to tag this issue for easier reference and refinement in the future, or not 😁.
