### ISSUE TITLE
Event manager never stopping when re-upload broken chunks

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#349]
**Describe the bug**
When you try to upload a website and that it fails for some reasons, you can see a warning message that indicates you that you need to re-upload the website again because some chunks haven't been received correctly by the blockchain. 
When you do so, the upload module (ie: event manager) starts and the chunks are being uploaded on the blockchain. 
Event though the chunks are all passed to the blockchain, the event manager never stops and so the user can stay block waiting forever. 

If you refresh the page, it works and you can see that your upload have been successful. 

**To Reproduce**

1. Go to websites page
2. Complete the upload module with needed info (wallet, website name, etc...)
3. Click on "Deploy to massa blockchain"
4. Once the container deployed, resolver set, and the 2 on X are uploaded, refresh the page.
5. See warning message on the uploaded website on the list below the upload module
6. Click on the 'ring icon' to re-upload your website
7. Upload the same website
8. Event manager starts 
9. Event manager never ends

**Expected behavior**
Once all the chunks are uploaded the event manager should stop and return to its initial state.

**Screenshots**

**Thyra version**
V0.1.0

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: firefox & chrome

**Comment by gregLibert** [comment]
This topic should be tackled when we rework the web-on-chain. @SlnPons , please feel free to tag this issue for easier reference and refinement in the future, or not 😁.
