### ISSUE TITLE
Refactor plugin manager mutexes

### ISSUE THREAD

**Issue by peterjah** [massalabs/station#433]
**Context**
Rework the use of mutexes for plugin manager.
The locks should be at an higher level (manager) to simplify the plugin code and avoid unexpected race conditions

**Comment by SlnPons** [comment]
@peterjah do you think this issue is a priority? I'm struggling to understand when this should be done...
Also, if you think that this could be handle by the run team maybe you could add more details? Cheers.

**Comment by longgamma-massa** [comment]
@peterjah what to do here?

**Comment by gregLibert** [comment]
This issue should be addressed during a plugin rework.
