### ISSUE TITLE
Update Website Deployer and thyra way to deploy SC with Constructor

### ISSUE THREAD

**Issue by SebastienValla** [massalabs/station#448]
Context
Thyra deploys the website deployers when someone uploads a new website.
Today we deploy a mainDeployer contract which includes the website site deployer contract bytecode, once deployed, it emits an event with the website deployer address.
The new way to deploy contracts is to use a constructor, we will need to change Thyra to handle differently the deployment and change the way we catch the website deployer address

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*

**How to**
*List the step-by-step to get it do if needed - PM*

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by SlnPons** [comment]
@SebastienValla can you add more details about why and how we should do this issue please? 
It will probably be handled by the run team so we need to make sure the context and the value are clear.
cc @thomas-senechal

**Comment by SlnPons** [comment]
Hey @B-Naoufal when updating the DNS SC and using latest massa-web3 standard, have you touched this point by any chance?
