### ISSUE TITLE
MassaStation on Windows - port 53 already used by WSL 

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#466]
**Context**
The default port for DNS is port 53. 
For Windows users using simulator and docker, this port is already used by WSL and so it's impossible for them to install and use MassaStation. 

We need to solve this issue properly.

**How to**

- [ ] Improve MassaStation install script for Windows to provide: (1) an relevant message to let them know that the port is already use; (2) provide them a solution
- [ ] Solution to be discuss within the Devs to identify the best one(s) 

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by SlnPons** [comment]
@ASAPSegfault can you add details directly on the description above if needed please? feel free to edit what I added. Thank you :)

**Comment by SlnPons** [comment]
https://github.com/massalabs/thyra/issues/276 - related issue

**Comment by thomas-senechal** [comment]
Another related issue: https://github.com/massalabs/station/issues/1055

**Comment by Thykof** [comment]
Hi @AurelienFT @jcbaillie 

We have an open pull request that fixes the conflict with WSL.

Here is the installer with this fix:
[massastation_installer_windows_fix_466_amd64.zip](https://github.com/massalabs/station/files/12259927/massastation_installer_windows_fix_466_amd64.zip)

Can you give it a try and tell us it it works?

**Comment by jcbaillie** [comment]
Just tried (after making sure it was uninstalled first), and unfortunately we get the same error:

<img width="386" alt="image" src="https://github.com/massalabs/station/assets/986939/de175196-2630-4247-9f21-edf912b24972">

Lots of red lines in the console log too, but way to fast to be able to read them, and then they disappear.

**Comment by Thykof** [comment]
Thanks for you feedback! This error is known and can be safely ignored (we might work on it to silent it). It should not prevent you from using Massa Station. Can you tell me if Massa Station can run and if you can access to `https://station.massa`?

**Comment by jcbaillie** [comment]
Yes, I continued past the error and successfully launched Massa Station. However https://station.massa does not work and gives the same error on Brave:

```
station.massa’s DNS address could not be found. Diagnosing the problem.
DNS_PROBE_POSSIBLE
```
 (chrome gives: DNS_PROBE_FINISHED_NXDOMAIN)

**Comment by Pierregvx** [comment]
Hi @jcbaillie can you tell me if the last line in your file `C:\Program Files (x86)\Acrylic DNS Proxy\AcrylicConfiguration.ini` is `LocalIPv4BindingAddress=127.0.0.1` ?

**Comment by jcbaillie** [comment]
It is not. It's 0.0.0.0 instead:

```LocalIPv4BindingAddress=0.0.0.0```

**Comment by Thykof** [comment]
> Just tried (after making sure it was uninstalled first), and unfortunately we get the same error:
> <img alt="image" width="386" src="https://user-images.githubusercontent.com/986939/258399336-de175196-2630-4247-9f21-edf912b24972.png">
> 
> Lots of red lines in the console log too, but way to fast to be able to read them, and then they disappear.

See this issue about remove this error dialog popup: https://github.com/massalabs/station/issues/1065

**Comment by jcbaillie** [comment]
OK, so I uninstalled massa station. The `Acrylic DNS Proxy\` folder was still there, but empty (it might be because I had a buffer still open in it somewhere). `NET STOP "AcrylicDNSProxySvc"` returns `the service name is invalid`, which suggests that it has indeed been properly uninstalled. I then removed the empty folder, just to be sure, and reinstalled.

The long list of red logs in the console logs during the install process are gone, and the `C:\Program Files (x86)\Acrylic DNS Proxy\AcrylicConfiguration.ini` file now properly contains the line `LocalIPv4BindingAddress=127.0.0.1` at the end. However unfortunately Massa Station is still unable to resolve https://station.massa/

NB: I tried to install Massa Station on another computer I have, which is running Windows 11 instead of Windows 10 (but not WSL) and indeed everything works like a charm.

**Comment by jcbaillie** [comment]
```
$ wsl --version
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3271
```

```
$ wsl -l
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
Ubuntu-20.04
```

`wsl -s` is used to set the default distro, I don't think this is what you meant.

PS: I'm on Discord if you want a more interactive loop, just sent you a friend request ;)

**Comment by Pierregvx** [comment]
[Screencast from 07-08-2023 16:08:07.webm](https://github.com/massalabs/station/assets/83134981/d3da0120-3970-45c8-8c99-125515be56dd)
worked properly on my win10 vm

**Comment by thomas-senechal** [comment]
For testing purposes:

[massastation_installer_windows_amd64.zip](https://github.com/massalabs/station/files/12302898/massastation_installer_windows_amd64.zip)

**Comment by jcbaillie** [comment]
still unable to access station.massa on my W10 machine.

**Comment by thomas-senechal** [comment]
Closing since this issue has been solved, and current bugs have been reported in https://github.com/massalabs/station/issues/1083
