### ISSUE TITLE
Add native lib for IOS and MacOS

### ISSUE THREAD

**Issue by gregLibert** [massalabs/station#5]

**Comment by qdrn** [comment]
To create the lib for iOS we need to use gomobile (https://medium.com/stack-me-up/meet-the-coolest-tech-marriage-flutter-go-369cf11367c9) to get the .framework:
`gomobile bind -target ios`
This returns the following error:
`gomobile: binding "main" package (github.com/massalabs/thyra-native-library) is not supported`.
I guess we should change a bit the go structure to be able to compile against ios target.

**Comment by gregLibert** [comment]
@qdrn I'm not sure that going back to gomobile is a good idea. Can you try the commands from [here](https://njkhanh.com/compile-golang-as-a-mobile-library-p5f3134373139) ?

**Comment by gregLibert** [comment]
A mobile version of Massa Station is currently not planned in our roadmap.
