### ISSUE TITLE
Registry page fix error handling

### ISSUE THREAD

**Issue by ASAPSegfault** [massalabs/station#502]
**Context**
On the registry page Thyra loads all websites associated with the DNS it communicates with.
However if the DNS associates the name of a website with a wrongly formatted address it produces an error when we try to read a key that doesn't exist and prevent the loading of all the other websites on the registry page.

**How to**
If a key doesn't exist on a SC from which we're trying to fetch the website metadata, handle this error properly and keep displaying reachable websites.

**Comment by SlnPons** [comment]
@thomas-senechal @SlnPons let's to reproduce this problem to be able to understand the pb and how we can solve it.

**Comment by SlnPons** [comment]
Closing this issue as can't reproduce after multiple tries.

**Comment by SlnPons** [comment]
@B-Naoufal @Thykof do you know if the work we have done on the DNS SC and its security prevent this from happening now?

**Comment by Thykof** [comment]
I don't know but we need to check

**Comment by SlnPons** [comment]
@B-Naoufal can you check this morning please? And let us know

**Comment by B-Naoufal** [comment]
@SlnPons this issue should be closed , ie checked and cannot reproduce , maybe with the changes we made on dns we already fixed the bug

**Comment by SlnPons** [comment]
How do we do to move from a "maybe" to a "I am sure"? 😅
This has been identified as a security problem so I would like to make sure that it's solved before closing it.

**Comment by Thykof** [comment]
I think @ASAPSegfault is saying that here:
- https://github.com/massalabs/station/blob/1e603fa0df5d03e6e5e888e3bc3f447a3b9479ca/int/api/websites/all.go#L77
- https://github.com/massalabs/station/blob/1e603fa0df5d03e6e5e888e3bc3f447a3b9479ca/int/api/websites/all.go#L82
we shouldn't return an error, but rather `continue` the `for` loop, right?

**Comment by ASAPSegfault** [comment]
Indeed it looks like this would solve the matter

**Comment by B-Naoufal** [comment]
@Thykof i just succeed reproduce the errors using my dns deployer script , the idea is when the website storer address is not in a format of an address or nil , the whole search page is broken , i am working on a fix , but if you want to reproduce just change the dns in the yaml file in thyra to this one : `AS12RsqDwktfxfTygPcxRt9mqoW3kn5sWJvqWLdfLstaTCxJsFvni`

**Comment by B-Naoufal** [comment]
Fixed.
