### ISSUE TITLE
Can't edit a website with a `.zip` file of 1MB or larger

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/station#509]
**The problem(s)**
When trying to edit a website with a `.zip` file that is larger that 1MB, nothing happens.
The GUI asking for the password doesn't show up as usual.

Thyra becomes unresponsive, refreshing the webpage does nothing and the page is loading infinitely, opening a new webpage to access Thyra does the same. Thyra needs to be restarted to work again.

It looks like the API call from the Front End seems to never be received by Thyra API as it's always shown as `pending` in my WebBrowser devtools.

**To Reproduce**

1. Clone Thyra repository
2. Upload a website of any size (less and more than 1MB worked)
3. Wait for the website to be fully uploaded
4. Click on the `Edit` button of the website and select a `.zip` of a website larger than 1MB
5. See that Thyra becomes unresponsive 

**Expected behavior(s)**

The `.zip` file should be uploaded normally.

**Thyra version**

[`main`](https://github.com/massalabs/thyra/tree/e7bf34b27e5045b78365e8b5f464a5ac920ba6bb)

**Desktop**
 - OS: MacOS
 
 **Any other useful info**
I tried to add some logs in the [`uploadWebsiteHandler`](https://github.com/massalabs/thyra/blob/ccc79ca19c820ab0e80043cb4da5520c21f1eb79/int/api/websites/webcreator.go#L95) function to find out where the issue is, but those logs were not displayed. So it looks like the API call never goes to the `uploadWebsiteHandler` function.

**Comment by gregLibert** [comment]
This topic should be confirmed/checked when we rework the web-on-chain. @SlnPons , please feel free to tag this issue for easier reference and refinement in the future, or not 😁.
