### ISSUE TITLE
Create a template for Thyra Plugins

### ISSUE THREAD

**Issue by SebastienValla** [massalabs/station#553]
**Context**
In order to onboard community easily we should have a template and a doc explaining how to create a plugin with best practise

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*

**How to**
*List the step-by-step to get it do if needed - PM*

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by gregLibert** [comment]
Done with https://github.com/massalabs/station-massa-hello-world
