### ISSUE TITLE
Duplicate plugin in the list

### ISSUE THREAD

**Issue by Thykof** [massalabs/station#566]
**The problem(s)**

I see two plugin in the list with same name.

**To Reproduce**

install plugin manually

install plugin with URL

**Expected behavior(s)**

In the front end, see only ONE plugin

**Screenshots**

![image](https://user-images.githubusercontent.com/11590067/228508062-eaeec812-2bce-41c5-bd67-513b51089262.png)

**Thyra version**
The version of Thyra the bug is present in.

Thyra commit sha: 7a5927a

**Desktop (please complete the following information):**
 - OS: MacOS 

 **Any other useful info**

**Comment by SlnPons** [comment]
This will be addressed as part of the work to improve the plugin manager.

**Comment by Thykof** [comment]
this is a bug concerning the deprecated frontend
