### ISSUE TITLE
Plugin aliases list isn't updated correctly

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/station#574]
**The problem(s)**
It's possible to register a Plugin multiple times. There are 2 issues with this:
- The Alias list isn't updated correctly and the previous plugin alias is still stored in the list which makes registering a plugin with the same Author/Name impossible.
- A malicious entity could register all plugins to make them unavailable (by changing their alias).

**To Reproduce**

1. Install Thyra
2. Install a plugin ([hello-world](https://github.com/massalabs/thyra-plugin-hello-world) for example)
3. Use Postman to get the ID of the Hello World Plugin
4. Use Postman to register with the ID of the Hello World Plugin
5. Try to reinstall the Hello World plugin using Postman (`POST /plugin-manager`)
6. See error in Thyra logs

**Expected behavior(s)**

As discussed [in those comments](https://github.com/massalabs/thyra/pull/564#discussion_r1151708597); 
> thyra need to reject the registry of the same plugin if it's already existing 

So, if a plugin is already registered, it shouldn't be possible to register it again.

**Screenshots**
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/44696378/228503339-7d5a1036-c6da-42ad-85a7-5bcab0f6c950.png">

**Thyra version**
v.0.1.11

**Desktop:**
 - OS: MacOS, Windows, Linux
 
**TODO:**

- [ ] Test `POST /plugin-manager/register` (https://github.com/massalabs/thyra/issues/562)

**Comment by SlnPons** [comment]
@Thykof @thomas-senechal is this still a behaviour that exist now?
And do you think we should address this before the mainnet? 

I lost track of the criticality for this ticket, sorry.

**Comment by thomas-senechal** [comment]
> @Thykof @thomas-senechal is this still a behaviour that exist now? 

I just tested it, and yes, we still have a problem mentioned in this issue:
- if we register a second time a plugin, the plugin become unavailable

But it looks like:
> The Alias list isn't updated correctly and the previous plugin alias is still stored in the list which makes registering a plugin with the same Author/Name impossible.

has been fixed, probably thanks to the use of a `Manifest.json` (if I'm not mistaking, the Manifests have been re-added after this issue got created)

> And do you think we should address this before the mainnet?

Yes since it will prevent malicious people from making plugins unavailable
But it's not a P1 IMO, and it should takes too long to fix
