### ISSUE TITLE
[web-on-chain] get the wallet URL dynamicaly

### ISSUE THREAD

**Issue by Thykof** [massalabs/station#590]
it would be nice to retrieve this endpoint dynamically. if we want to handle several wallets sometime

_Originally posted by @peterjah in https://github.com/massalabs/thyra/pull/581#discussion_r1158220810_

**Comment by gregLibert** [comment]
This topic should be tackled when we rework the web-on-chain. @SlnPons , please feel free to tag this issue for easier reference and refinement in the future, or not 😁.
