### ISSUE TITLE
Create internal documention /procedure about plugin store & updates

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#611]
**Context**
This issue is part of Thyra plan for the mainnet as Milestone 1 to build a robust plugin manager. 
All detail & info can be found [here](https://www.notion.so/massa-innoteam/Improve-polish-key-features-7f828de23fe840bd9d0ced892cb723d2?pvs=4#52642a42ecc44a77a7a5f9dd7679d23b)

--> the objective of this issue to create appropriate internal documentation for everyone to be able to manage and support plugin stores and updates. It must be crystal clear for every new or older team member.

**User flow**
As a inno team member, I want to understand how the plugin store and massa.station are working together so that I am able to handle any problem with it.

**How to**

here: https://www.notion.so/massa-innoteam/Add-a-plugin-in-the-store-7d95d5268bbd46c690ff7102abebd18f

- we can write the doc about how to add on the store, how to review the PR
- automated test (DONE)
- manual review of the PR: write review guideline so that any one form Massa Labs or community member to review
plugin validation
- we let for latter the plugin validation: Massa Labs policy regarding plugins acceptance
5 working days to merge or reject the plugin store review

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
Read and understand the mechanism without asking Q. to devs

**Comment by pivilartisant** [comment]
Notion for internal use until we are ready to release it to externals
Github for external (when it is released) because it seems to be the best platform because it allows clear documentation and is used in terms of our target audience.

**Comment by pivilartisant** [comment]
Link to first draft of the documentation on Notion : [here](https://www.notion.so/Plugin-store-publishing-procedures-020c39b59b6349adbedf0b587eb30d91?pvs=4). 
Will be revised and updated in the near future.

**Comment by pivilartisant** [comment]
Link to procedure in Notion - Inno Only - Procedure [here](https://www.notion.so/massa-innoteam/Plugin-store-publishing-procedures-1909820c7f78476288d20a3128621207?pvs=4)

The document will need to be revised and validated when plugin-store is implemented.

**Comment by SlnPons** [comment]
Current status: blocked for lack of knowledge internally to write this procedure correctly. 

The objective if this procedure is to enable anyone as Massa Labs to review and validate a new module (plugin) so it can be published and so accessible to end-users. 
As Massa Labs, we must assure end-users security and so write a simple and clear procedure with things that we must verify. The list of things is too complicated for the Inno team to define alone... 
Refinement and further discussions are needed.

**Comment by gregLibert** [comment]
This issue should be addressed during the plugin rework. @SlnPons, please let me know if you think my cleanup was excessive.
