### ISSUE TITLE
Doc: Enable external devs to create plugin

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#612]
**Context**
This issue is part of Thyra plan for the mainnet as Milestone 1 to build a robust plugin manager. 
All detail & info can be found [here](https://www.notion.so/massa-innoteam/Improve-polish-key-features-7f828de23fe840bd9d0ced892cb723d2?pvs=4#52642a42ecc44a77a7a5f9dd7679d23b)

--> this issue has for objective to create appropriate doc and support to enable external developers to build plugins

**User flow**

1. Dev-user comes on Massa Docs and click on the dedicated section of MassaStation
2. Dev-user finds info about what is Massa Station and how to build its how plugins 
3. Dev-user can push their plugins 
4. Dev-user can see their plugins on the list after having push a successful commit

**How to**

- [ ] Create a skeleton of the expected doc (titles + desc;) 
- [ ] Create doc using "hello world plugin"
- [ ] Create potential other support: update parts of github? swagger? 
- [ ] Be very specific about the process and the tech stack that can be used
* Make sure to mention that all plugins must allow CORS. The general rule is: we need to allow CORS for all the endpoints: routes and methods that our API define
- [ ] Be very specific about the support that we can or cannot provide

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

Dev doc: how to build a plugin:
- tuto build a plugin with the hello world plugin
- explain how to use Massa Station plugin manager (swager file)
- explain how to depends on the hello world plugin to register
- https://github.com/massalabs/docu-dev/issues/82

**QA testing**
Ask external dev to read and test (from core team or run team)

**Comment by Pierregvx** [comment]
got this with chatgpt for the skeleton, wdyt @SlnPons ?
## For Developers:

1. Introduction
   - Explain what MassaStation is and why a plugin manager is useful
   - Provide an overview of the documentation

2. Building Plugins
   - Plugin structure
      - Explain the basic structure of MassaStation plugins
      - Provide information on the different types of MassaStation plugins
   - Plugin requirements
      - Provide information on the technical requirements for building MassaStation plugins
      - Explain how to ensure compatibility with MassaStation
   - Use cases
      - Provide examples of common use cases for MassaStation plugins

3. MassaStation Store
   - Overview
      - Explain what the MassaStation Store is and its purpose
      - Provide an overview of the store's features and functionality
   - Accessing the store
      - Explain how to access the MassaStation Store
      - Provide information on how to browse available plugins
   - Search and filtering
      - Provide information on the search and filtering capabilities of the MassaStation Store

4. Pushing Plugins
   - Submission process
      - Explain how external developers can push plugins to the MassaStation Store
      - Provide information on how to submit a plugin for review
   - Review and approval process
      - Explain the process for reviewing, validating, and sharing information about new plugins submitted to the MassaStation Store
      - Provide information on how external developers can stay informed of potential requested changes or approval status
   - Listing plugins
      - Explain how to list plugins on the MassaStation Store
      - Provide information on how to ensure plugins meet store policies and requirements

5. API Reference
   - API documentation
      - Provide documentation for the MassaStation plugin manager API
      - Explain how to use the API to extend the functionality of the plugin manager

6. Best Practices
   - Developing plugins
      - Provide guidance on best practices for building MassaStation plugins
      - Explain how to optimize performance and ensure compatibility
   - Using the store
      - Provide guidance on best practices for using the MassaStation Store
      - Explain how to optimize search and filtering

**Comment by SlnPons** [comment]
Hey @Pierregvx I've created this page to keep working on the skeleton together: https://www.notion.so/massa-innoteam/Dev-doc-Plugins-creation-6017cb2da1314db4aad0cd8b33aa89f8?pvs=4 

I tried to improve the sections 3 and 4. Have a look and let me know what you think. 
About part 2, where I trust you more than myself to identify the correct info, you can use the "Hello world" plugin that is made for that (ie: it's an exemple - for the API connection, for the manifest etc...)

**Comment by Pierregvx** [comment]
> Hey @Pierregvx I've created this page to keep working on the skeleton together: https://www.notion.so/massa-innoteam/Dev-doc-Plugins-creation-6017cb2da1314db4aad0cd8b33aa89f8?pvs=4
> 
> I tried to improve the sections 3 and 4. Have a look and let me know what you think. About part 2, where I trust you more than myself to identify the correct info, you can use the "Hello world" plugin that is made for that (ie: it's an exemple - for the API connection, for the manifest etc...)

sounds good :)

**Comment by Thykof** [comment]
Action plan:
- write the doc directly in the docu-dev repo
- explain tech stack: you can build a plugin in go or other language
- what the plugin have to do to work this Massa Station (register, having a manifest, logo...)
- for plugin writing in go: use the hello-world plugin package to register (@SlnPons we will need to release this plugin but we are stuck for now)
- beeing listed on the store

**Comment by SlnPons** [comment]
@Pierregvx please make sure to validate the steps one by one to avoid going to far away without being the right direction ;)
And don't forget that this doc must be attractive to dev: do sth that yourself you will LOVE to read and use!! <3

1. write the doc directly in the docu-dev repo
2. explain tech stack: you can build a plugin in go or other language
3. what the plugin have to do to work this Massa Station (register, having a manifest, logo...)
--> I would say that here you can ask for a review already ;) 
Suggested reviewer: Greg + Nathan 
4. for plugin writing in go: use the hello-world plugin package to register (@SlnPons we will need to release this plugin but we are stuck for now)
5. being listed on the store

**Comment by Pierregvx** [comment]
> @Pierregvx please make sure to validate the steps one by one to avoid going to far away without being the right direction ;) And don't forget that this doc must be attractive to dev: do sth that yourself you will LOVE to read and use!! <3
> 
> 1. write the doc directly in the docu-dev repo
> 2. explain tech stack: you can build a plugin in go or other language
> 3. what the plugin have to do to work this Massa Station (register, having a manifest, logo...)
>    --> I would say that here you can ask for a review already ;)
>    Suggested reviewer: Greg + Nathan
> 4. for plugin writing in go: use the hello-world plugin package to register (@SlnPons we will need to release this plugin but we are stuck for now)
> 5. being listed on the store

about the 2, should I explain what needs to be in the register function the dev has to create if not using Go ?

**Comment by Thykof** [comment]
Normally the swagger is self explaining, if you think it's not, let's improve it. In the doc you put a link to the swagger.

**Comment by SlnPons** [comment]
@Pierregvx overall, I can't challenge the content. So I'll let other reviewers (developers) do it. 
But I've got 2 general comments: 
1. I don't understand if the "guidelines" come first and then the "creation". Is that the case? If so what's the objective of the guidelines exactly? It's not clear for me. 

2. Module vs. plugin: you are using both words without explaining them so it's very confusing. 
From a mkt point of view we decided to use the word "module" so if we want to introduce and use the word plugin: not a problem at all! :) But we should write 2 lines to explain that it's the same (maybe in the guidelines part)

**Comment by Pierregvx** [comment]
> @Pierregvx overall, I can't challenge the content. So I'll let other reviewers (developers) do it. But I've got 2 general comments:
> 
> 1. I don't understand if the "guidelines" come first and then the "creation". Is that the case? If so what's the objective of the guidelines exactly? It's not clear for me.

The guideline should come first, it aimed to address this part of the skeletton 

```
- Plugin Requirements:
   - Obtain information on the technical requirements for building MassaStation plugins.
```

Maybe I should rename it to `requirements`

> 2. Module vs. plugin: you are using both words without explaining them so it's very confusing.
>    From a mkt point of view we decided to use the word "module" so if we want to introduce and use the word plugin: not a problem at all! :) But we should write 2 lines to explain that it's the same (maybe in the guidelines part)

you're right I will correct that !

**Comment by SlnPons** [comment]
This needs to be done ASAP. Builders are blocked and people are waiting for it. 
So let's put more focus and ressources on this if needed!

**Comment by longgamma-massa** [comment]
@Pierregvx can you link PRs that should close this issue pls?

**Comment by leoloco** [comment]
I just pushed a draft of the Hello World plugin tutorial. I've thoroughly reviewed the process and would like to share some concerns.
As the name of the issue suggests, the goal of this tutorial is to enable external devs to create their plugin. It should also emphasize the fact that Massa Station is agnostic to the programming language and the plugin's features. Thus to me, the information of interest are: 
- What is a MS plugin
- How plugins communicate with MS and with other plugins
- How to register a plugin to MS
- How to add your plugin to the store

But, as it is today, I feel like the information of interest gets flooded into the go-swagger Rube Goldberg machine. It feels like a tutorial on go-swagger rather than a tutorial on MS plugins. Moreover, the three parts of this tutorial, (tic tac standalone API, "Hello <Name>" endpoint, and front end) seem totally unlinked. 

I feel like the `station-massa-hello-world` was not designed as an educative tool but rather as an internal experimental project. Thus I suggest that, for future version of the documentation, we work on creating a hello-world project that better fits our pedagogical needs.
