### ISSUE TITLE
Add Website Missing Chunks endpoints tests

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/station#614]
**Context**
Following https://github.com/massalabs/thyra/issues/514 , we need to test every parts of Thyra endpoints using the Robot Framework. The task has been divided in sub issues to allow parallelisation of endpoint testing.

**How to**

- [ ] Write tests endpoint for `POST /websiteCreator/uploadMissingChunks`
- [ ] Write a test for "big websites"

**Technical details**
- We need to find a way to upload a website with missing chunks.
- We need to find what is a "big websites" (TBD by a `.zip` file weight in `Mo`)

**Comment by gregLibert** [comment]
This topic should be tackled when we rework the web-on-chain. @SlnPons , please feel free to tag this issue for easier reference and refinement in the future, or not 😁.
