### ISSUE TITLE
Use multi arch binaries for MacOs

### ISSUE THREAD

**Issue by peterjah** [massalabs/station#624]
**Context**
Using the tool "Lipo" is seems possible to package MacOs binary for multi architectures (arm/amd) into a single one.
see: https://dev.to/thewraven/universal-macos-binaries-with-go-1-16-3mm3

I think it would be great to have only 1 MacOs binary for Thyra and every golang softwares (plugins)

**How to**
Modify the CI to build this multi arch binary using Lipo
Take in consideration the impacts on install scripts. maybe there is addaptation to do

**QA testing**
The binary works both on macOs arm and amd

**Comment by SlnPons** [comment]
cc @thomas-senechal have you seen this?
