### ISSUE TITLE
Change the redirection link to "Format info" into Web On Chain plugin page

### ISSUE THREAD

**Issue by maxime-carabina** [massalabs/station#638]
**Context**
When you are on the Web On Chain plugin page, the redirection link to the "format info" is not the right one.

Link TBD because hte documentation about this part is missing on the Github.

**User flow**
The user flow that must be tested is the following:

1. Go on WebOnChain plugin page
2. Click on “format info” link

**How to**

change wording: "I want to upload a website"
link: "Massa Docs tutorial"

**Technical details**

**QA testing**

**Comment by SlnPons** [comment]
As soon as it's unblocked, it's the main priority

**Comment by gregLibert** [comment]
@longgamma-massa @Thykof is this issue up to date ?

**Comment by Thykof** [comment]
yes, as soon as this PR https://github.com/massalabs/docs/pull/92 is merge, it will unblock this issue because we will have the link to the documentation page to upload a website. 

It might require UI/UX guidelines to implement this issue, also wording ("format info").

**Comment by longgamma-massa** [comment]
Relates to Upload website featue and: https://github.com/massalabs/station-massa-wallet/issues/671

**Comment by gregLibert** [comment]
This topic should be tackled when we rework the web-on-chain. @SlnPons , please feel free to tag this issue for easier reference and refinement in the future, or not 😁.
