### ISSUE TITLE
The dns my.massa is not set during installation

### ISSUE THREAD

**Issue by Elli610** [massalabs/station#656]
The dns my.massa is not set during installation thus, to connect to thyra you must go through "localhost/..." and not through "my.massa/..."

I don't know what caused the bug. 
I built thyra by myself following the [CONTRIBUTING](https://github.com/massalabs/thyra/blob/main/CONTRIBUTING.md) file and, because I am on windows 11, I changed the "go build -o thyra-server cmd/thyra-server/main.go" to "go build -o thyra-server.exe cmd/thyra-server/main.go"

Thyra version:
I didn't use a release but here is the [last commit](https://github.com/massalabs/thyra/commit/fcffdce3f36524a57b0140e86cfa77d9e97807d0) which was present on the main branch.
The last release was 0.1.14.

Computer info:
 - OS: Windows 11 (22H2)
 
How i fixed it: 
I had to run `NETSH interface ipv4 set dnsservers "Wi-Fi" static 127.0.0.1 primary` and `NETSH interface ipv6 set dnsservers "Wi-Fi" static ::1 primary`

Things I tried before fixing it:
- Re-install thyra from scratch
- Run `RestartAcrylicService.bat` from C:\ProgramFile(x86)\Acrylic...
- Run [this script](https://github.com/massalabs/MassaStation-Installer/blob/main/windows/scripts/configure_network_interfaces.bat)

**Comment by SlnPons** [comment]
Hey @Elli610 to make sure we solve this problem could you: 
* specify what you were trying to do exactly? 
* how we can reproduce this problem? 
Your inputs are detailed but not knowing your end-goal prevent me from looking at the right problem 😅

Cheers

**Comment by Elli610** [comment]
> Hey @Elli610 to make sure we solve this problem could you:
> 
> * specify what you were trying to do exactly?
> * how we can reproduce this problem?
>   Your inputs are detailed but not knowing your end-goal prevent me from looking at the right problem 😅
> 
> Cheers

I needed to use the new api endpoints to update the wallet-provider which had not yet been merged.  
This is what I did:
- I installed the last release
- I saw that the new endpoints weren't merge that hadn't been merge yet
- I Followed the instructions in the contributing file to build thyra
- and then the bug appeared

Hope that helps

**Comment by gregLibert** [comment]
This topic should be tackled when we rework the web-on-chain. @SlnPons , please feel free to tag this issue for easier reference and refinement in the future, or not 😁.
