### ISSUE TITLE
Plugin interrupt error when exiting

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/station#672]
**The problem(s)**
"plugin 'thyra-plugin-node-manager' exiting with error: signal: interrupt" error when stopping Thyra using CTRL+C.

**To Reproduce**

1. Start `thyra-server`
2. Do CTRL+C to shutdown Thyra
2.1. If you can't see the error, reproduce from step 1. Sometimes, it doesn't appear.
3. See error

**Expected behavior(s)**
Plugins should be stopped gracefully.

**Screenshots**
```
2023/05/22 17:40:18 [POST /plugin-manager/register] Name: Node Manager ID:819
^C2023/05/22 17:40:19 Shutting down...
2023/05/22 17:40:19 plugin 'thyra-plugin-node-manager' exiting with error: signal: interrupt
2023/05/22 17:40:19 Stopped serving thyra server at http://[::]:80
2023/05/22 17:40:19 Stopped serving thyra server at https://[::]:443
```

**Thyra version**
[latest main](https://github.com/massalabs/thyra/tree/dd7b69e2056de13805167232a0eb7662ef38fee0)

**Desktop:**
 - OS: MacOS (probably also happens on the other OSs, to be confirmed)
 
 **Any other useful info**
- To make it happen all the time, just add a `time.sleep(1 * time.Second)` at the end of `stopServer` https://github.com/massalabs/thyra/blob/dd7b69e2056de13805167232a0eb7662ef38fee0/int/api/server.go#L43
- I think we should add a `StopAll` function to the PluginManager and call this function when stopping Thyra
- We could also call a specific endpoint of a plugin to tell it to shutdown, and if it doesn't, we shut it down after a given timeout

**Comment by SlnPons** [comment]
@thomas-senechal do you manage to reproduce this error please? 
And do you experience it with other plugin? (eg: Massa Wallet)

**Comment by thomas-senechal** [comment]
> @thomas-senechal do you manage to reproduce this error please? 

Yes

> And do you experience it with other plugin? (eg: Massa Wallet)

Not with the Wallet and the Hello World plugin. I guess it's because they are build with `Go Swagger` which contains a way to Shutdown Gracefully the API in case of `CTRL+C`. But the node manager still "crashes". 

IMO, we still need to address this issue since the error is there because MassaStation doesn't shutdown plugins "gracefully" when it stops

**Comment by thomas-senechal** [comment]
Also, `CTRL+C` is used when MassaStation is started from a terminal. 
But when we use the GUI and we close it, plugins are still running -> I just tried, and the wallet and node manager are still running with MassaStation closed

**Comment by SlnPons** [comment]
Yes, ok so it's not just bug. It's really about improving the way Massa Station handle the shutdown of the plugins. 
Especially the fact that when Massa Station is turned OFF, all plugins should be as well.
This is an important problem that people highlighted during the audit of the wallet (as an exemple) 

Thanks @thomas-senechal for the details. 
Do you have a straightforward solution in mind already? Or does it need to be discussed?

**Comment by thomas-senechal** [comment]
> Do you have a straightforward solution in mind already? Or does it need to be discussed? 

In the technical section, i added 2 points about it:
- simply to add a "StopAll" function to the plugin manager that will stop all plugins with the code we already have. And we will call it when closing Massastation. 
- improve the function that stops a plugin to first, send a shutdown request to the plugin, and if it doesn't close after x seconds, we kill the plugin. 

IMO, we should for now focus on fixing the issue with plugins shutdown and so, go with option one which will be enough for now. 
And if one day we really need to let plugins stop by themselves, we will implement it later. 

So, i don't think we really need to discuss about it, it mainly depends on your needs

**Comment by Thykof** [comment]
I experience this bug on macos amr64 with wallet plugin

**Comment by SlnPons** [comment]
`I think we should add a StopAll function to the PluginManager and call this function when stopping Thyra` --> @peterjah do you think we need to implement this before mainnet?

On the user side, it's hidden for all users except the MacOS users that can see, for instance the wallet-plugin terminal opens even after shutting down massa station. 
So im happy to prioritise it because I don't find this very good but I don't realise how complex or needed it is....

**Comment by SlnPons** [comment]
ERRATUM: For a MacOS user, the above comment is wrong and this wrong behaviour is NOT hidden as even after quitting Massa Station you still have the wallet plugin terminal open. 
Let's try to solve this out before the mainnet, it's not critical but it's not really professional.

**Comment by Elli610** [comment]
> And sometimes, the plugins just won't stop: ![image](https://user-images.githubusercontent.com/44696378/240279692-f215a40b-4142-4b6f-adb8-bb8b53e9b8b4.png)

Same on windows 11
