### ISSUE TITLE
[SC] - Revert setResolver operation if dnsName not valid - Display website naming rules

### ISSUE THREAD

**Issue by Trottoir** [massalabs/station#69]
The `setResolver` transaction must fail if the dnsName is not only composed of :
- lower case letter
- numbers

**Comment by SlnPons** [comment]
Hey @Trottoir, this issue has been addressed (#68 ). Can you confirm?
If yes, can you close it please? Cheers

**Comment by Trottoir** [comment]
Not on the smart contract side.
An user can directly call the setResolver function without using our UI / API

**Comment by SlnPons** [comment]
Why is it blocked @Trottoir please? 
Happy to remove this from the backlog for now, as I think it's better to address after the pluggenisation.

**Comment by SlnPons** [comment]
@AurelienFT Do you know if the reason why an operation fails is now shared on testnet 17? If not yet, do you know if it's planed soon? 
Not urgent on your side but just so I have an idea of when to address this issue. Cheers :)

**Comment by AurelienFT** [comment]
> @AurelienFT Do you know if the reason why an operation fails is now shared on testnet 17? If not yet, do you know if it's planed soon? Not urgent on your side but just so I have an idea of when to address this issue. Cheers :)

If an operation fails all the events you displayed are reverted but we will change this for testnet 18. Even if you don't have your event if you make your operation fail using an `abort` for example, there is an event raised that has this format : 
```
{ "massa_execution_error": [ERROR] }
```
that you can fetch using the `operation_id` filter.

**Comment by SlnPons** [comment]
For the Inno/team to check if this exist or not

**Comment by Thykof** [comment]
DNS smart contract now checks the name: https://github.com/massalabs/massa-standards/blob/main/smart-contracts/assembly/contracts/dns/dns.ts#L37

I think we can close this issue

**Comment by SlnPons** [comment]
Woww finally! Perfect :) 
thanks for helping me to clean the repo @Thykof <3
