### ISSUE TITLE
No plugin can be added to thyra under windows

### ISSUE THREAD

**Issue by Elli610** [massalabs/station#694]
When we want to add a plugin to thyra. For instance the wallet-plugin: 
we go to "https://my.massa/thyra/plugin-manager/index.html" and paste the url of the release of the wallet-plugin that we want to install, it displays "Error while installing plugin". In the console of the browser we find the following error messages:

- Error: downloading plugin at https://github.com/massalabs/thyra-plugin-wallet/releases/download/v0.0.12/wallet-plugin_windows-amd64.zip: renaming plugin wallet-plugin: rename C:\Users\hervi\Documents\Massa\thyra\plugins\wallet-plugin\wallet-plugin_windows-amd64 C:\Users\hervi\Documents\Massa\thyra\plugins\wallet-plugin\wallet-plugin: The system cannot find the file specified.

- I also got this one but IDK if it's related: POST https://my.massa/plugin-manager?source=https://github.com/massalabs/thyra-plugin-wallet/releases/download/v0.0.12/wallet-plugin_windows-amd64.zip 500

The problem obviously comes from the fact that the installer is looking for a binary file to rename in a plugins folder, but I'm on windows so it should be looking for the same file with the ".exe" extension.

I solved this issue by manually renaming the "wallet-plugin_windows-amd64.exe" to "wallet-plugin.exe".

I built thyra from [this commit](https://github.com/massalabs/thyra/commit/21a4f28df08192453c066bae989c9c67dbc2970f)

OS : Windows 11 (22H2)
 
Finally, no plugin can be added to thyra under windows because of this problem

cc @thomas-senechal

**Comment by Thykof** [comment]
I can reproduce with Massa Station version 0.2.3, I'm working on it

**Comment by SlnPons** [comment]
@Thykof can you do the QA of this ticket please? 
I don't have windows 11 :( 

I'll ask external users to do it too but I prefer try internally firs :)

**Comment by Thykof** [comment]
I made the fix, so it works for me, better if someone else in the team can QA. @maxime-carabina could you do it?

**Comment by maxime-carabina** [comment]
> I made the fix, so it works for me, better if someone else in the team can QA. @maxime-carabina could you do it?

@SlnPons I've just tested it and everything works for me.
