### ISSUE TITLE
Add the "up vote / down vote" function to DNS smart contract

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#696]
**Context**
This is a prequisite to build the new registry page (that will be renamed "Massa ecosystem" page when redesigning).
Check the design for more details and rules to implement.

**Designs**
https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=1026-11415&t=T5nG2J1jIFuTqunH-0

**User flow**
1. Users install MassaStation
2. Users access the "Search Massa ecosystem" page
3. Users clicks on the up or down arrow
4. Users see a MassaStation (wails) pop-up asking them to connect to a wallet
5. Users connect to MassaWallet
6. Users select an account
7. Users sign a transaction

**How to**

- [ ] Suggest the rules associated to this function (how many time a user can vote, do we store who vote, do we anonymise the vote etc...)
- [ ] Suggest different ways of assigning the storage fees
- [ ] Validate above with MassaStation team
- [ ] Implement the Voting function in the DNS smart contract
- [ ] Think about best user flow and validate it with MassaStation team

**Technical details**
TBD

**QA testing**
Follow the user flow and/or designs.

**Comment by gregLibert** [comment]
This topic should be tackled when we rework the web-on-chain. @SlnPons , please feel free to tag this issue for easier reference and refinement in the future, or not 😁.
