### ISSUE TITLE
We cannot retrieve the operation Id during the interaction with a smart contract

### ISSUE THREAD

**Issue by Elli610** [massalabs/station#698]
We cannot retrieve the operation Id during the interaction with a sc when using the cmd/executeFunction endpoint. We only receive a string that contains the first generated event. 

This is problematic when you need several events, the content of the return of a method or even to retrieve the operationID (for the wallet-provider for instance)

cc @SlnPons @gregLibert

**Comment by gregLibert** [comment]
@SlnPons this is blocking the wallet-provider and the front DApp refacto.
