### ISSUE TITLE
the cmd/executeFunction enpoint doesn't work anymore

### ISSUE THREAD

**Issue by Elli610** [massalabs/station#699]
When using the cmd/executeFunction endpoint, it sends the transaction to be signed using the old api url (rest/wallet/) so it doesn't work.

I had to locally change 2 lines in "thyra/pkg/node/sendoperation/sendoperation.go" for it to work:

- [L31](https://github.com/massalabs/thyra/blob/main/pkg/node/sendoperation/sendoperation.go#L31) -> const WalletPluginURL = "http://my.massa/thyra/plugin/massalabs/wallet/api/"

- [L117](https://github.com/massalabs/thyra/blob/main/pkg/node/sendoperation/sendoperation.go#L117) -> WalletPluginURL+"/accounts/"+nickname+"/sign",

latest commit which modified the sendoperation.go file: https://github.com/massalabs/thyra/commit/6ed827ad08400adc0d1e716992a8e26ac01d3be3 

cc @SlnPons @gregLibert

**Comment by gregLibert** [comment]
@SlnPons this is blocking the wallet-provider and the front DApp refacto.

**Comment by Thykof** [comment]
@Elli610 I don't understand what you need. 

/cmd/executeFunction is declared here https://github.com/massalabs/thyra/blob/main/api/swagger/server/restapi/resource/swagger.yml#L71

**Comment by Thykof** [comment]
This is because you use Thyra with the wallet on branch main.

Wallet plugin on branch main has breaking changes in its API. We will release it in the following days under v0.1.0

**Comment by Thykof** [comment]
@Elli610 do you get time to check #795 ?

**Comment by Elli610** [comment]
> @Elli610 do you get time to check #795 ?

I didn't expect the new version to keep the first event but that's not a problem for me.
it's all good for me

**Comment by Thykof** [comment]
> > @Elli610 do you get time to check #795 ?
> 
> I didn't expect the new version to keep the first event but that's not a problem. it's all good for me ty

yeah I kept the event for backward compatibility, we will be able to remove it later if nothing use it.

I would need another review to merge the PR #795

**Comment by Elli610** [comment]
> > > @Elli610 do you get time to check #795 ?
> > 
> > 
> > I didn't expect the new version to keep the first event but that's not a problem. it's all good for me ty
> 
> yeah I kept the event for backward compatibility, we will be able to remove it later if nothing use it.
> 
> I would need another review to merge the PR #795

Done !

**Comment by Thykof** [comment]
FYI, because we still listen for the first event, this take some time. If you wanted to only have the operation id to have the response ASAP, then the fact that I left the event for compatibility might not be that much a good idea.

If you want the operation id ASAP when you call this endpoint, and if nothing and no-one need the event in the response, then we should probably remove the listen of the event to save time.
