### ISSUE TITLE
Most a POST arguments when calling the cmd/executeFunction endpoint are never used in thyra's code

### ISSUE THREAD

**Issue by Elli610** [massalabs/station#700]
Most a POST arguments when calling the cmd/executeFunction endpoint are never used in thyra's code.
Some like fee and coins even have an identical description.

Unused arguments and duplicates should be removed

cc @SlnPons @gregLibert

**Comment by Thykof** [comment]
> Unused arguments and duplicates should be removed

Or maybe should be used ^^

**Comment by Elli610** [comment]
> > Unused arguments and duplicates should be removed
> 
> Or maybe should be used ^^

Hi ! 
API Definition: https://github.com/massalabs/station/blob/main/api/swagger/server/restapi/resource/swagger.yml#LL51C15-L106C33
Which is used here: https://github.com/massalabs/station/blob/main/int/api/cmd/execute_function.go#LL23C34-L23C41
The code only uses: 
- Args
- Nickname
- At
- Name
- Coins

Thanks to @thomas-senechal

**Comment by Thykof** [comment]
Something concerning is linter saying:

pkg/node/sendoperation/executesc/executesc.go:33:38: unused-parameter: parameter 'coins' seems to be unused, consider removing or renaming it as _ (revive)
func New(data []byte, maxGas uint64, coins uint64, dataStore []byte) *ExecuteSC {

**Comment by SlnPons** [comment]
@Thykof @peterjah tbh I don't really understand if this issue is critical for massa station. 
Should we address this before going public?

**Comment by Thykof** [comment]
bug user story: As a developer I use this Massa Station endpoint and some argument are ignored.

let me have a closer look to list what argument are ignored to see if it's critical.

But to say it simply: cmd/executeFunction exists and work, but lacks customization

**Comment by Thykof** [comment]
we don't use:
- Expiry: Set the expiry duration (in number of slots) of the transaction.
- Fee: Set the fee amount (in massa) that will be given to the block creator.
- Gas price: Price of a gas unit.
- Gas limit: Maximum number of gas unit that a node will be able consume.
- KeyID: Defines the key to used to sign the transaction.

**Comment by Thykof** [comment]
# QA:
I send http request to cmd/executeFunction and look at the prompt I see, here are the results:
- fee for executeFunction endpoint: OK
- gas.price for executeFunction endpoint: KO
- gas.limit for executeFunction endpoint: no gas limit in the prompt
- coins for executeFunction endpoint: OK
- expiry for executeFunction endpoint: looks good
