### ISSUE TITLE
Implement an api endpoint to allow read only calls to smart contract

### ISSUE THREAD

**Issue by Elli610** [massalabs/station#701]
Allowing read-only calls on smart contracts is essential. This allows users to read public values present in contracts without having to pay for a transaction since these operations do not modify the state of the blockchain.

cc @SlnPons @gregLibert

**Comment by SlnPons** [comment]
Isn't the objective of the block API?

**Comment by Elli610** [comment]
IDK. What is this ?

**Comment by SlnPons** [comment]
Not a question for you @Elli610 😅 sorry. Will handle this and come back to you, no worries :)

**Comment by gregLibert** [comment]
> related to #1269 because we are adding a function to do the read only call.
> 
> This issue can benefit from the presence of that function to just add the endpoint and plug to that function.

Should we close this issue then ?

**Comment by Thykof** [comment]
> > related to #1269 because we are adding a function to do the read only call.
> > This issue can benefit from the presence of that function to just add the endpoint and plug to that function.
> 
> Should we close this issue then ?

no, we have now the functions to estimate gas for a callsc and execute sc, we need to add endpoints to expose those functions (if it's a need).

something like:
- POST /cmd/estimate-gas/callsc
- POST /cmd/estimate-gas/executesc

**Comment by Thykof** [comment]
we have another PR to merge
