### ISSUE TITLE
Write logs on disk

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/station#717]
**Context**
For now, we are using golang `log` library to print logs in the terminal. But since we are now using the GUI, and so, no more terminals, the logs are unavailable to the users unless they start MassaStation from a terminal. To solve this issue, we need to store logs on a file on disk to allow users to send us the logs for debug.

**User flow**

- User starts MassaStation
- An error occurs
- MassaStation logs the error in a file
- The user retrieves the file and attaches it to an issue to allow devs to find the issue and fix it

**How to**
- TBD

**Technical details**
- A way of storing the information on disk and still print them in the terminal is to do this:
  ```go
  f, err := os.OpenFile("massastation.log", os.O_RDWR|os.O_CREATE, 0644)
  if err != nil {
  	log.Fatalf("error opening file: %v", err)
  }
  defer f.Close()
  wrt := io.MultiWriter(os.Stdout, f)
  log.SetOutput(wrt)
  ```
  The main issue of this code is that it must be stored in the `main` function for the `defer` to only happen when we exit. We could also make our own `Logger` that would wrap `log` and do the above code. But that might be a waste of time, so we might just want to make a class that will perform the above code and has a function to "close" the logger such as: 

  ```go
  type logger struct {
	f   *os.File
	wrt io.Writer
  }

  func newLogger() *logger {
	f, err := os.OpenFile("massastation.log", os.O_RDWR|os.O_CREATE, 0644)
	if err != nil {
		log.Fatalf("error opening file: %v", err)
	}
	wrt := io.MultiWriter(os.Stdout, f)
	log.SetOutput(wrt)
	return &logger{f, wrt}
  }

  func (l *logger) close() {
	l.f.Close()
	l.wrt = nil
  }

  func main() {
	logger := newLogger()
	defer logger.close()
  ...
  ```

**QA testing**
- TBD

**Comment by SlnPons** [comment]
@gregLibert @peterjah i've got some pending questions for you on this issue. Could you have a look and share your opinion please? 
With Thomas, we have identified this as an important and urgent must have. Do you share this feeling too?

- Do we need to stock 1 single file "massastation.log" that we override at each launch? (Est ce que l'on stock 1 seul fichier "massastation.log" que l'on override à chaque lancement ?)
OR do we stock X files based on the date (eg: 01-20-2023-12h29.log, 03-24-2023-09h17.log...) 

- Does every plugin manage its own logs? (Est ce que chaque plugin se gère pour les logs?)
- Where should stock the logs for each OS? Maybe you know what's the default behaviour for Linux?

**Comment by gregLibert** [comment]
> Do you share this feeling too?

Yes

> Do we need to stock 1 single file "massastation.log" that we override at each launch?

One file but no override for now.

> Does every plugin manage its own logs?

Yes

> Where should stock the logs for each OS?

I suggest:
- Linux: /var/log
- MacOS: /Library/Logs
- Windows: in the massa directory ?

**Comment by Thykof** [comment]
FYI https://github.com/massalabs/station/issues/460

**Comment by Pierregvx** [comment]
we decided to put the logs in the massastation directory for all os

**Comment by SlnPons** [comment]
@Pierregvx please add an estimation before starting to work on a task :) 
Let's get back to the good habits and apply the DoR.

**Comment by SlnPons** [comment]
KO this caused a bug on Windows 11 because the massa directory is not accessible.... 
cc @gregLibert (this is the problem that Brian & John had)

**Comment by Thykof** [comment]
issue: https://github.com/massalabs/station/issues/930
