### ISSUE TITLE
We need to fix the cmd/executeFunction endpoint

### ISSUE THREAD

**Issue by Elli610** [massalabs/station#730]
**Context**
*Describe / explain why we should do this: motivations, context or other info. Keep it brief and simple - PM*
I realized that the endpoint cmd/execute function had problems

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*
I need you to fix the following point:
Some arguments specified in the swagger (https://github.com/massalabs/thyra/blob/main/api/swagger/server/restapi/resource/swagger.yml#L71-L158):
- have identical descriptions
- Are obviously never used in thyra's code
Also, arguments that represent a number of MASSA tokens (coins, fee, ..) would be better represented as bigint (passed as a string in the request) and using the smallest MASSA unit.

**How to**
*List the step-by-step to get it do if needed - PM*
- check the endpoint and fix the issues I raised and maybe some others I didn't see)

**Comment by Thykof** [comment]
is it a duplicate of https://github.com/massalabs/station/issues/700?

**Comment by Elli610** [comment]
> is it a duplicate of #700?

looks like it is. mb

**Comment by Thykof** [comment]
Then I close it, feel free to add detail in #700 

@SlnPons I added #700 in our board
