### ISSUE TITLE
Remove PostMan collection

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/station#741]
**Context**
API tests are now using Robot Framework to run, so we don't need the tests in the Postman collection anymore. Also, since we are using Swagger to define our API, and the fact that Postman allows us to import it, we don't need the Postman collections anymore.

**How to**
- Delete the Postman collection

**Technical details**
- Postman collections are stored here: https://github.com/massalabs/thyra/tree/e25eef54d5901ea16dddd7258ee09481a3e794a0/api/test

**Comment by B-Naoufal** [comment]
covered in https://github.com/massalabs/station/pull/800
