### ISSUE TITLE
Document how to use postman with the swagger spec

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/station#742]
**Context**
Following https://github.com/massalabs/thyra/issues/741 , Postman collections will be deleted in favor of importing the Swagger file. We need to add some documentation explaining how to import it.

**User flow**
- Reads the dev documentation
- Finds a documentation explaining how to use Postman
- Follow the steps to import the Swagger file in Postman

**How to**
- Update the `CONTRIBUTING.md` file to explain how to import the Swagger file into Postman

**Technical details**
- The Swagger file is here https://github.com/massalabs/thyra/blob/e25eef54d5901ea16dddd7258ee09481a3e794a0/api/swagger/server/restapi/resource/swagger.yml
- As explained in [this comment](https://github.com/massalabs/thyra/issues/558#issuecomment-1588912020):
  > the baseURL variable isn't set right after importing the Swagger file

  We need to make sure this variable is set by default. If it's not possible, we need to make sure to tell people to update it right after importing the Swagger file.

**QA testing**
- Install Postman : https://www.postman.com/downloads/
- Follow the documentation to import the Swagger file
- Check if you can run it

**Comment by SlnPons** [comment]
@thomas-senechal I'm not sure to understand the purpose of this ticket. 
If we decided to use swagger instead of postman, isn't it enough? Why do you think we need to help user to install and import swagger into postman? (is it standard in dev.doc?)

**Comment by thomas-senechal** [comment]
> @thomas-senechal I'm not sure to understand the purpose of this ticket. 
> If we decided to use swagger instead of postman, isn't it enough? Why do you think we need to help user to install and import swagger into postman? (is it standard in dev.doc?)

That was a request from @gregLibert : https://github.com/massalabs/station/issues/558#issuecomment-1588929735

It is usual to have Postman collections for an API. It allows devs to call endpoints easily, without having to write the API call by themselves. 

We had some Postman collections, but a lot of endpoints were missing from the collections, and some endpoints have not been updated for months in the collection. 
But since we can just import the Swagger file inside Postman, we don't need collections anymore. But people (devs) might not know about importing a Swagger file in Postman, so explaining it will allow devs to perform API calls from Postman and they will be sure that it is up to date since we use it to generate the API

**Comment by SlnPons** [comment]
This issue is in progress for a week + now. Is there any blockers?

Also after checking what have been written so far, I don't think we're going in the right direction....it's way too low level. We're talking to developers about sth very basic, there is no need to add that many screenshots and steps to explain how to use postman.
Please check how others (google, apple...) are writing their documentation, ask chat GPT, and produce high quality documentation. If you don't know how to do this, ask for help.

**Comment by B-Naoufal** [comment]
> No there is no blockers , the PR was already approved once , and we were waiting for a second review to merge.

**Comment by SlnPons** [comment]
> > No there is no blockers , the PR was already approved once , and we were waiting for a second review to merge.

Ok so in that case: 
1. The issue shouldn't be "in progress" but in code review. 
2. Please address my comments above :)

**Comment by B-Naoufal** [comment]
closed by : https://github.com/massalabs/docu-dev/issues/125
