### ISSUE TITLE
Replace "thyra" by "massastation" in the code

### ISSUE THREAD

**Issue by B-Naoufal** [massalabs/station#748]
**Context**
Replace "thyra" by "massastation" everywhere in the code.

**How to**

- [x] #756
- [x] #762
- [x] #797
- [x] #771
- [x] Replace "thyra" by "massastation" in test files and .robot files.
- [x] #830

**Comment by SlnPons** [comment]
@B-Naoufal can you update this issue with missing details please? 
What's the rest in to do?

**Comment by B-Naoufal** [comment]
Its done i will close it
