### ISSUE TITLE
Unblock windows user: use installed certificates

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#805]
**Context**
Windows users can't access https pages because when new certificates are installed, the browser app needs to fully closed to take into account certificates just installed. 

We must help windows users to know that they need to close their browser app to access the right links. 
See reported bug here: https://github.com/massalabs/station/issues/758

**User flow**
1. Install massa station 
2. See massa station icon on your desktop
3. Click on it to open massa station application
4. Click on "open massa station" 
5. Access station.massa/home/ and see a header that explained that: 
* Scenario 1: user has followed Windows installation step by step and correctly installed the certificated (ie: we detect the certificated), we invite user to close their browser application (not just the tab, the browser app should be quit and launch again)
* Scenario 2: user hasn't followed the installation correctly, they haven't given the permission to install the certificates (can't detect certificates) then user sees a header with a link to the installation process / FAQ (tbd)

**How to**

- [ ] Create header on the home page to display correct message based on user flow above 
- [ ] Try to see if we can detect certificates or not
- [ ] If we can't detect installed certificates, then display a generic message for windows users ONLY and redirect to a documented page describing both problem and step-by-step solution

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
Follow user flow above

**Comment by SlnPons** [comment]
Please see https://github.com/massalabs/station/issues/758 
Maybe this solution is not the right one

**Comment by gregLibert** [comment]
I think we should first undestand why it's not working.
This task should be done after investigation, see #758
