### ISSUE TITLE
Store page - Add validation rule to the manual plugin if a plugin is already installed

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#854]
**Context**
Currently, users can install plugins manually (ie: plugins that aren't listed in the store) and this is very convenient we should keep it. 

But when a user tries to install a plugin that is already installed then the error message is not relevent. We should handle nicely this business case. 

See details here: https://github.com/massalabs/station/pull/803#issuecomment-1602314518

**User flow**

User should see an explicit error message. 
Please to define the error message, check the error message that exist for the search page > website name when the name already exist and use the same format (sujet / verbe / complement or imperatif). Error messages must be consistent across all the app :)

**How to**

- [ ] Create this validation rule in the BE 
- [ ] Create this validation rule in the FE

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by gregLibert** [comment]
This issue should be addressed during the plugin rework. @SlnPons, please let me know if you think my cleanup was excessive.
