### ISSUE TITLE
Search page Fix "connect wallet" button 

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#878]
**The problem(s)**
As a user, when I don't have a massa wallet created but I have massa wallet plugin installed, I should see a "Create wallet" button or a "Connect wallet" button rather than an "install wallet" button as the wallet is already installed.

**To Reproduce**
Use massa station latest version and the search page

**Expected behavior(s)**
--> show a "Create wallet" button that redirect to the massa wallet home page when massa wallet is installed on massa station but not wallet are creted yet.

**Screenshots**
<img width="1510" alt="image" src="https://github.com/massalabs/station/assets/109611779/cc0e1016-ed38-4644-8835-54a49a6b5080">
<img width="1509" alt="image" src="https://github.com/massalabs/station/assets/109611779/b9af7da6-7a35-4269-be1d-308e8718e59f">

**MassaStation version**
Latest on the main monday 26th of june at 9am

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by Thykof** [comment]
It works well if you refresh the page. To reproduce: 
- delete the wallet plugin
- install the wallet plugin
- go to search page
- see "Install wallet" button
