### ISSUE TITLE
Logo problem on Windows

### ISSUE THREAD

**Issue by maxime-carabina** [massalabs/station#882]
**The problem(s)**
Once installed on Windows 11, the application appears in the menu, but not the logo.

![image](https://github.com/massalabs/station/assets/72019005/c7dad07c-1815-4639-be88-27ae4168c51a)

Here, however, you can see that it is present in the icon tray.
![image](https://github.com/massalabs/station/assets/72019005/5fd63003-2218-4948-b7e3-54e45e45584d)

**To Reproduce**
- Download `.msi` file here for Windows : https://github.com/massalabs/station/releases/tag/v0.2.3
- Follow steps to install : https://github.com/massalabs/station/blob/main/INSTALLATION.md
- Open Windows menu and search `MassaStation`

**Expected behavior(s)**
The application logo in the menu should be the same as the one in the icon tray.

**Comments**
On MacOS and Linux, we are using fyne to package the app as a .App for MacOS, and an archive on Linux that contains the icon and other stuff useful to add the icon for MassaStation on the App list.
But on Windows, we cannot use fyne because it needs to rebuild the .exe, but it always fails. So we only use go to build the binary, which does not add a logo to the .exe.

IMO, we need to find a way to add the icon to the binary after building it.
[josephspurrier/goversioninfo](https://github.com/josephspurrier/goversioninfo) might be a solution, needs further investigation

**MassaStation version**
version : 0.2.3

**Desktop (please complete the following information):**
Windows 11

**Comment by Thykof** [comment]
potential solution here https://github.com/massalabs/station/pull/924#discussion_r1250816653

**Comment by pivilartisant** [comment]
base on our research if we pursue what @Thykof started : https://github.com/massalabs/station/compare/main...882-logo-problem-on-windows

and add the following at line 251. : 

``` 
     <Directory Id="DesktopFolder" Name="Desktop">
                <Component Id="ApplicationShortcutDesktop" Guid="3e6f0b0e-1e0b-5a3c-7b0c-9c007a32f0e9">>
                    <Shortcut Id="ApplicationDesktopShortcut"
                        Name="{PRODUCT_NAME}"
                        Target="[#MassaStationRunScript]"
                        WorkingDirectory="INSTALLDIR"
                        Icon="MassaStationIcon"
                    >
                        <Icon Id="MassaStationIcon" SourceFile="MassaStationLogo" />
                    <Shortcut/>
                    <RemoveFolder Id="ApplicationShortcutDesktop" On="uninstall" />
                    <RegistryValue Root="HKCU" Key="Software\{MANUFACTURER}\{PRODUCT_NAME}" Name="DesktopShortcut" Type="integer" Value="1" KeyPath="yes" />
                </Component>
                </Component>
            </Directory>
            </Directory>
        </Directory>
        </Directory>
```

**Comment by pivilartisant** [comment]
after investigating on 

We (@Pierregvx @maxime-carabina  and I) are blocked by the current error : https://github.com/massalabs/station/pull/968

```
Windows Installer XML Toolset Compiler version 3.14.0.6526
Copyright (c) .NET Foundation and contributors. All rights reserved.

config.wxs
Windows Installer XML Toolset Linker version 3.14.0.6526
Copyright (c) .NET Foundation and contributors. All rights reserved.

D:\a\station\station\installer\buildmsi\config.wxs(84) : error LGHT0094 : Unresolved reference to symbol 'Icon:MassaStationIcon' in section 'Product:*'.
D:\a\station\station\installer\buildmsi\config.wxs(102) : error LGHT0094 : Unresolved reference to symbol 'Icon:MassaStationIcon' in section 'Product:*'.
Getting version from git tags
Error building installer:  Command '['wixtoolset\\light.exe', '-ext', 'WixUIExtension', '-ext', 'WixUtilExtension', '-sval', '-out', 'massastation_0.2.4_amd64.msi', 'buildmsi\\config.wixobj']' returned non-zero exit status 94.
```

**Comment by Thykof** [comment]
It's probably because of the way you specifu sourceFile of the icon, see  for example how the target is passed: `Target="[#MassaStationRunScript]"`

**Comment by pivilartisant** [comment]
After a morning investigation I have set the logo extension to .ico and imported a placeholder logo in the build dir here is the error I have : 
```
Run python windows/build_installer.py
Getting version from git tags
Error building installer:  [Errno 2] No such file or directory: '..\\int\\systray\\embedded\\logo.ico'
Error: Process completed with exit code 1.
```

This afternoon I will invesitgate the dir and also try to directly embed the path to the file when calling it in the  : 

```xml
<shortcut
icon=desktopicon
...
>
<icon id ="desktopicon" sourcefile="path/to/file" 
</shortcut>

**Comment by SlnPons** [comment]
@pivilartisant I don't have windows, could you ask people that you've tested this issue with to add screen shots of the logo please? 
Make sure that we can the pixel or not ;) 

Expected screens: 
* Windows 11
* Windows 10

**Comment by pivilartisant** [comment]
@Thykof @maxime-carabina @LucasF243 @Pierregvx :)

**Comment by Thykof** [comment]
I tested before merging, it's pretty :)

**Comment by pivilartisant** [comment]
it seems that w11 user don't get the pretty logo

**Comment by Thykof** [comment]
I tested on windows 11 it was ok
