### ISSUE TITLE
Change position of DropDown account selection

### ISSUE THREAD

**Issue by maxime-carabina** [massalabs/station#886]
Move `DropDown` for account slection in the `SidePanel`.

![image](https://github.com/massalabs/station/assets/72019005/e04ac475-7e51-49f5-a2df-2700e30d55c7)

**Comment by SlnPons** [comment]
KO I now have the account drop down in 2 diff places... 
Is that expected? 
@LucasF243 @maxime-carabina I guess you had the conversation together because this wasn't agreed with me.... so please solve this out.

**Comment by Thykof** [comment]
Yes it is expected, we didn't touch the dropdown in the layout (all pages) to rework it in another PR concerning the network switch https://github.com/massalabs/station/pull/896#pullrequestreview-1500897123
