### ISSUE TITLE
Massa Station screen scroll weird behavior

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/station#905]
**The problem(s)**
The scroll on the app pages seem to have a bizarre behavior. The components rendered are cut when they exceed a certain position. 

**To Reproduce**
Open Massa Station app and navigate to home page, scroll on 

**Screenshots**
https://github.com/massalabs/station/assets/90157528/6dd9159b-a693-4a6f-8f9c-0cd8d6bf865c

**MassaStation version**
0.2.3

**Desktop (please complete the following information):**
MacOS Ventura M2 MacbookAir

**Comment by pivilartisant** [comment]
@SlnPons is this what you expected for the scroll behavior ? cf video

**Comment by SlnPons** [comment]
hummm I'm not sure where this issue is coming from @pivilartisant. Could you explain this to me?

**Comment by pivilartisant** [comment]
> hummm I'm not sure where this issue is coming from @pivilartisant. Could you explain this to me?

Short explanation :

AS IS:
The user scrolls on the child component and home page separately creating a difference between the global screen and the local child component scroll (cf video) 

SHOULD BE ? : 
the user scrolls and only the page is reactive not the page + the child component 

Long explanation : 
The issue is most likely coming from the FE -> it seems like the layout component encapsulates children components (like the store or dashboard) because it has a fixed height. The consequence of this is that when the user scrolls on the child component the scroll is only triggered on the child component. 

@maxime-carabina  since we discussed about this earlier, do you agree with this ?

**Comment by SlnPons** [comment]
Ok, very clear @pivilartisant sorry I was confused because I thought it was an old issue regarding the home page that we discussed with the rest of the team.

**Comment by SlnPons** [comment]
Solved by: https://github.com/massalabs/station/issues/908
