### ISSUE TITLE
upload: Handle zip too big

### ISSUE THREAD

**Issue by Thykof** [massalabs/station#906]
**Context**
*Describe / explain why we should do this: motivations, context or other info. Keep it brief and simple - PM*

In the new frontend, on page search, in the right side panel to upload a website on the blockchain, the zip file has a limit max size in Mo.

We must show a proper error message to the user when the user try to upload a zip file beyond that limit.

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*

**How to**
*List the step-by-step to get it do if needed - PM*

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

- [ ] add a `else if` here https://github.com/massalabs/station/blob/d5a7137ecbe6f435034db4483548448fab6a5905/web/massastation/src/components/SidePanels/Upload/Upload.tsx#L88 to handle the API response code `WebCreator-1003` returned here https://github.com/massalabs/station/blob/da32ae8815b5dce93ccfbe36990fbaf2690e7524/int/api/websites/prepare.go#L115. Show a message "your webiste must be less than XX Mo". 

- [x] in https://github.com/massalabs/station/blob/e7271bbe293f36f2a83be12eebe3b98b4f872e55/web/massastation/src/validation/upload.ts#L46-L47 add a function to validate the size of the file using https://developer.mozilla.org/en-US/docs/Web/API/Blob/size. Show the same message "your webiste must be less than XX Mo". 

This way, the form validation handle the zip size and the API response case is handled.

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

Try to upload bug websites: 
- [big-website.zip](https://github.com/massalabs/station/files/11895031/big-website.zip)
- [very-big-website.zip](https://github.com/massalabs/station/files/11895028/very-big-website.zip)
and see error message

**Comment by SlnPons** [comment]
Looks good :) 
Just for me to know, where have added this validation rule for now @B-Naoufal please? (front-end & back-end?)

**Comment by Thykof** [comment]
We added it to the frontend, the backend already did this check so now user can't validate the form if exceeded size, to anticipate error from the backend
