### ISSUE TITLE
Remove scroll bar style from browser 

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/station#908]
**Context**
It is more esthetic to remove the scroll bar apparition

**User flow**
The user scrolls and there is no ugly scroll bar 

**How to**
see [here](https://dev.to/derick1530/how-to-create-scrollable-element-in-tailwind-without-a-scrollbar-4mbd)

Firefox on MacOs :
<img width="1470" alt="Screenshot 2023-06-28 at 15 56 22" src="https://github.com/massalabs/station/assets/90157528/c2115485-415a-4957-ad73-841cd35d92c7">

Chrome on Ubuntu 22.04
![Screenshot from 2023-06-28 16-01-53](https://github.com/massalabs/station/assets/90157528/ac765898-0b37-468e-b462-628deac31eed)

**Comment by SlnPons** [comment]
What's the difference with: https://github.com/massalabs/station/issues/905?

**Comment by pivilartisant** [comment]
> What's the difference with: #905?

the objective of this PR is to remove the scroll bar from actually appearing (still works) it is an esthetic proposition

**Comment by MJAlaeddini** [comment]
Why is the issue open when the problem is solved?

**Comment by SlnPons** [comment]
Hey @MJAlaeddini check comments on the PR. It's not solved yet...

**Comment by Thykof** [comment]
already fixed
