### ISSUE TITLE
Add Cypress

### ISSUE THREAD

**Issue by mazmassa** [massalabs/station#912]
**Context**
We don't have any setup defined for our acceptance (e2e) tests.

**User flow**
N/A

**How to**
N/A

**Technical details**
We must install and configure Cypress to be able to create our acceptance tests. This will allow us to do that and many other interest things in terms of tests. Much more that the current one we already have using Jest.
This must be set in all repos: Wallet, Station and even in UI-Kit.

**QA testing**
N/A

**Comment by SlnPons** [comment]
@mazmassa what's the point of cypress? 
I guess i've got the same question for this ticket here https://github.com/massalabs/ui-kit/issues/10 ;)

**Comment by mazmassa** [comment]
> @mazmassa what's the point of cypress? I guess i've got the same question for this ticket here [massalabs/ui-kit#10](https://github.com/massalabs/ui-kit/issues/10) ;)

✅
