### ISSUE TITLE
Happy Path Test

### ISSUE THREAD

**Issue by mazmassa** [massalabs/station#913]
**Context**
We don't have ANY acceptance (e2e) tests.

**User flow**
N/A

**How to**
N/A

**Technical details**
We must add at least one happy path acceptance test for each main feature. Happy path test is the minimum successful test coverage for a main action on the feature.
In case of the wallet, for example, start a transfer until we conclude it is the happy path. We don't test errors, details or constrains in the middle. We just assert and cover whole correct flow assuming users will do correctly each step from the beginning until end. The other cases or users deviations we cover in other tests. If we add the happy path we at least ensure the whole correct flow works fine.

We'll use Cypress for that! This task has dependency on https://github.com/massalabs/station/issues/912

**QA testing**
N/A

**Comment by SlnPons** [comment]
@mazmassa what's the "happy" path test please? 
Could you add more info in the description so it's easier to prioritise. Especially because I would like to add many different tests and the run team will be in charge of that so we need to be specific ;)
Cheers

**Comment by mazmassa** [comment]
> @mazmassa what's the "happy" path test please? Could you add more info in the description so it's easier to prioritise. Especially because I would like to add many different tests and the run team will be in charge of that so we need to be specific ;) Cheers

Just updated! Let me know if is clear please!

**Comment by SlnPons** [comment]
Label question added to make sure that: define the most important scenarios to cover so we can prioritise and address them one by one rather than trying to do everything at once :)

**Comment by pivilartisant** [comment]
Closing because we have added happy path test
