### ISSUE TITLE
TS Interfaces/Types

### ISSUE THREAD

**Issue by mazmassa** [massalabs/station#917]
**Context**
We have a bunch of Interfaces/Types created on the fly when writing our page/components. As a good practice and to turn code scalable we must take care of that before it becomes unmaintainable.

**User flow**
N/A

**How to**
N/A

**Technical details**

- [ ] We should first remove the `export` word for the ones that are not exported. 

- [ ] Secondly, we must identify the ones that are duplicated by one or more attrs and merge in only one. 

- [ ] Finally, for the exported ones we must extract them into a specific file in the same dir of the file component.

**QA testing**
N/A

**Comment by SlnPons** [comment]
@mazmassa could you help me to prioritise this by adding a bit more details about the benefit of doing such a correction please?
Faster? More scalable?

**Comment by mazmassa** [comment]
> @mazmassa could you help me to prioritise this by adding a bit more details about the benefit of doing such a correction please? Faster? More scalable?

✅

**Comment by pivilartisant** [comment]
moved to Technical clarification

Why ? 

We want to discuss the naming standards with @mazmassa before acting
