### ISSUE TITLE
Fix wails Pop Up Size 

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/station#919]
**Context**
The size of the wails pop up does not correspond to the design 

**How to**
Change the wails - react front end code 

**Technical details**
![Screenshot from 2023-06-29 09-28-23](https://github.com/massalabs/station/assets/90157528/161fd49f-2513-48e4-be1a-1c6795432dee)

**Comment by SlnPons** [comment]
@pivilartisant what's the rational to fix the size of the pop-up instead of addressing the responsiveness of it? 
I'm not sure to see the value for end user of fixing it.

**Comment by pivilartisant** [comment]
> @pivilartisant what's the rational to fix the size of the pop-up instead of addressing the responsiveness of it? I'm not sure to see the value for end user of fixing it.

this not the correct repo for this issue ( my bad sorry). I will close the current one and ping you on the new one with correct information.

**Comment by pivilartisant** [comment]
new issue : https://github.com/massalabs/station-massa-wallet/issues/483
