### ISSUE TITLE
Remove Account Persistence on Zustand

### ISSUE THREAD

**Issue by mazmassa** [massalabs/station#922]
**Context**
We are storing in local browser storage unnecessary content.

**User flow**
 There's NO UX/UI involved here. Pure tech aspects.

**How to**
- Open the browser, switch/select an account.
- Open the console, pick Application tab.
- 
You should see the accounts content stored.

**Technical details**
We have some stores already defined in Zustand.

Between them we have one called **Account** that is persisted in the browser local storage. We should remove that persistence once it does not make sense (now) to have it.

**QA testing**
- Open the browser, switch/select an account.
- Open the console, pick Application tab.

You should not see any account content stored.

**Comment by SlnPons** [comment]
Hey @mazmassa thanks for the issue. Could you add more info about the user benefit in the description please? 
Without the info in the template, it's hard to prioritise because it's hard to compare ;)
Cheers

**Comment by mazmassa** [comment]
> Hey @mazmassa thanks for the issue. Could you add more info about the user benefit in the description please? Without the info in the template, it's hard to prioritise because it's hard to compare ;) Cheers

Just updated!

**Comment by Thykof** [comment]
I think we implemented that way to anticipate a UX requiring selection of the account across pages

**Comment by mazmassa** [comment]
> I think we implemented that way to anticipate a UX requiring selection of the account across pages

The way we did was storing the whole object in the storage... what is definitely not good. We should persist only the address. Just did that for bridge we can use the same logic.
