### ISSUE TITLE
Prevent terminal to open when launching Massa Station on Windows 10 & 11

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#923]
**Context**
When you install Massa Station using the installation script, a terminal opened on your desktop. This is not normal and should be preveted

**User flow**
As a user, when I install Massa Station using the installation script, I don't want to see any technical windows openening. I simply want to see that the installation is successful, the icon on my desktop and the browser opening to the home page.

**How to**

- [ ] Prevent terminal to open
- [ ] Test e2e to make sure that windows 11 is compliant with expected user flow described above

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
Follow user flow

**Comment by thomas-senechal** [comment]
Also appeared on my W10 computer a few days ago

**Comment by Thykof** [comment]
@peterjah @gregLibert WDYT about this solution?

**Comment by gregLibert** [comment]
> @peterjah @gregLibert WDYT about this solution?

I have no objection. i would simply comment it as i'm not a professional of windows vbs:

```vbscript
' Create a WScript Shell Object
Set oShell = CreateObject("Wscript.Shell")

' Command to be run
Dim strArgs
strArgs = "massastation.exe"

' Use the Run method of the WScript Shell object to run the command.
' The second parameter 0 means "hidden window"
' The third parameter false means the script will not wait for the program to finish execution before continuing to the next statement
oShell.Run strArgs, 0, false
```

**Comment by SlnPons** [comment]
Half solved: the terminal opens but closes after a couple of seconds. Which, at this stage, has been judged as acceptable. 
Here is the ticket to address this problem fully: https://github.com/massalabs/station/issues/984
