### ISSUE TITLE
Log permission denied prevent MassaStation to launch

### ISSUE THREAD

**Issue by Thykof** [massalabs/station#930]
**The problem(s)**

2023/06/29 14:55:58 open C:\Program Files (x86)\MassaStation\massastation.log: Access is denied.

**To Reproduce**

Install Massa Station v0.2.4 on Windows

Run Massa Station .

**Expected behavior(s)**

Massa Station launches

**Screenshots**

**MassaStation version**
The version of MassaStation the bug is present in.

v0.2.4

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows...]

Windows 11, not test on other OS
 
 **Any other useful info**
To see the error:
```
cd "C:\Program Files (x86)\MassaStation\"
 .\massastation.exe
```

**Comment by Pierregvx** [comment]
I'ts related to this pr https://github.com/massalabs/station/pull/899
I didn't test it on windows

**Comment by Pierregvx** [comment]
solution we chose:
* create a logs folder with the right authorisations in windows
* write the logs in this folder
