### ISSUE TITLE
MassaStation crashes if there is no internet access

### ISSUE THREAD

**Issue by Pierregvx** [massalabs/station#939]
**Describe the bug**
If the user doesn't have any connection, the server crashes because the store can't be fetched
so the user can't access massastation without internet

to solve : replace the logger.fatal to logger.error if the store can't be fetched
**To Reproduce**

remove wifi
click on the massastation icon
nothing happens

**Expected behavior**
launch normally 

**Screenshots**
![image](https://github.com/massalabs/ui-kit/assets/83134981/2bb596c5-9415-4863-9684-545098a247fd)

**Version**
0.2.4-dev
**Additional context**

**Comment by Pierregvx** [comment]
[Screencast from 03-07-2023 11:34:53.webm](https://github.com/massalabs/station/assets/83134981/2fdb31ec-d181-445d-9b23-134fdaffcf69)

**Comment by B-Naoufal** [comment]
i think we should create another issue in the topic of no internet , because once the user is offline , the pages are showing loading .. but instead we need to display a header with msg like you are offline please check your connection ...
<img width="1489" alt="image" src="https://github.com/massalabs/station/assets/16125633/a682a6bf-e3bc-43c8-8c46-3dddc91c19d5">

**Comment by Pierregvx** [comment]
> i think we should create another issue in the topic of no internet , because once the user is offline , the pages are showing loading .. but instead we need to display a header with msg like you are offline please check your connection ...
> 
> <img alt="image" width="1489" src="https://user-images.githubusercontent.com/16125633/251449453-fb49aa67-9a2a-467c-a8a4-f9299ddda164.png">

I agree, WDYT @pivilartisant @SlnPons ?

**Comment by Pierregvx** [comment]
> 2 things here:
> 
> 1. Checking for product validation at the end of the process is a problem. Please follow the DoR!!! It's nightmare to work like this and it's even more frustrating that I keep repeating that every day.
>    Having this kind of comment in CR is not acceptable.

I don't see why this does not respect the DoR. The issue raised by @B-Naoufal is related to this topic but not included to this one witch is just a change in the logs, and this is about the front end , I did not detect this because I just tried to run massastation ( without accessing the frontend) 

> 2. I flagged this ticket as needed for the release so if you need a validation or a discussion, please be PROACTIVE and come get the info... you can't just wait and see!

sorry about that I should have ping you 

> That is said, it is not clear what is the current behaviour with the fix you suggest @Pierregvx can you show me? + have you tested on all the OS as expected?

I only tested on ubuntu as it does not depend on the os, 
before this pr : massastation can't run without internet
after : it runs but logs an error

**Comment by Thykof** [comment]
I tested on macos it works too. Nothing OS specific in the PR #966
