### ISSUE TITLE
Add missing logs in massastation.logs

### ISSUE THREAD

**Issue by Pierregvx** [massalabs/station#944]
**Context**
these 2 logs are found in the console but missing in the log file
 * to initiate the https server : `Serving massastation at ...`
 * in the certificates errors
They are not written with the Logger created

**User flow**
* delete mkcert
* run massastation 
* open https://station.massa

**How to**
replace old logs with the Logger created 
**Technical details**
* replace loggings : `fmt.Errorf/Printf`, with the logger in the missing places
* Set a custom logging function using `config.Logger` in the server so that swagger logging can be set in the logging file in `configure_massastation.go`

**QA testing**
* run massastation
* check if the logs are written in the file :

  * run `grep "Serving massastation" /usr/local/share/massastation/logs/massastation.log`
  * it should not be empty
* to test the certificate errors : 
  * remove the mkcert folder with  `rm -rf /home/pierre/.local/share/mkcert `
  > station.massa won't be allowed to run on https
  * run massastation
  * click on the icontray to access station.massa in https
  * this will provoque a certificate error, check that it is shown in the logs

**Comment by SlnPons** [comment]
@Pierregvx could you add more details in this ticket based on the conversation we had on the chat please? 
If needed close this issue. But let's make sure we don't work toward a wrong objective here ;) Cheers
