### ISSUE TITLE
Windows Installation - Failure keep DNS set to 127.0.0.1 (rollback)

### ISSUE THREAD

**Issue by gregLibert** [massalabs/station#945]
On windows 11, when the installation has failed and it's roolback, the DNS is still set to 127.0.0.1 which is blocking internet access...

**Comment by Thykof** [comment]
I have reproduce the bug. 

I can see in the installation logs:
```
CustomAction ConfigureAcrylic returned actual error code 1 (note this may not be 100% accurate if translation happened inside sandbox)
MSI (s) (A8:0C) [09:18:08:555]: Note: 1: 1722 2: ConfigureAcrylic 3: C:\Program Files (x86)\MassaStation\ 4: cmd /c "C:\Program Files (x86)\MassaStation\configure_acrylic.bat" 
Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action ConfigureAcrylic, location: C:\Program Files (x86)\MassaStation\, command: cmd /c "C:\Program Files (x86)\MassaStation\configure_acrylic.bat" 
MSI (s) (A8:0C) [09:18:11:180]: Product: MassaStation -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action ConfigureAcrylic, location: C:\Program Files (x86)\MassaStation\, command: cmd /c "C:\Program Files (x86)\MassaStation\configure_acrylic.bat" 

Action ended 9:18:11: InstallFinalize. Return value 3.
...
Action 9:18:11: Rollback. Rolling back action: [1]
1: ConfigureAcrylic 
```

The even though I have wifi connected, I don't have internet access.

To fix internet access: run `C:\Program Files (x86)\Acrylic DNS Proxy\InstallAcrylicService.bat`

**Comment by Thykof** [comment]
This commit fix the bug but by removing the rollback step that uninstall acrylic service. So internet access is not broken if installation failed, but DNS and acrylic stay configured.

**Comment by Thykof** [comment]
I reopen because we would like to create a proper rollback mechanism.

**Comment by thomas-senechal** [comment]
As explained here: https://github.com/massalabs/station/pull/1080#issuecomment-1669538005
We can't QA this since the only way to reproduce the issue is to modify the scripts.
