### ISSUE TITLE
Update Testnet 23.2

### ISSUE THREAD

**Issue by ASAPSegfault** [massalabs/station#947]
**Context**
This issue and the associated branch will serve as the working version of Thyra on testnet 23.2.
All other issues regarding updates to testnet 23 should be merged here in order for the product to be fully QAed
for testnet 23

**Comment by SlnPons** [comment]
@ASAPSegfault and team, please note that Massa Station will be updated to use the latest version of the testnet at the same time as the buildnet is upgrading. It will limit the work we need to do. 
So maybe that Massa Station won't be compatible with testnet 23.2 but testnet 24 directly.... let's see.
