### ISSUE TITLE
[BACK] - RPC client must be initialized on main function

### ISSUE THREAD

**Issue by Trottoir** [massalabs/station#96]
AS IS : 
We create an instance of the RPC client each time we call an endpoint

TO BE : 
`client := node.NewDefaultClient()` is only instantiated once

**Comment by SlnPons** [comment]
@Trottoir I think has been done, can you confirm and close the issue if yes? cheers

**Comment by Trottoir** [comment]
This has not been done ! 
It's a 100% technical issue quite straightforward but can be long.

**Comment by gregLibert** [comment]
If we revisit the node's connection management, this optimization could be considered. However, it might be overly ambitious at this stage.
