### ISSUE TITLE
Installation failed on macOS: command not found: brew

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/station#987]
**The problem(s)**
Failed to install MAssa station from the dedicated installer.

```
./postinstall: Updating Brew...
./postinstall: zsh:1: command not found: brew
./postinstall: FATAL: brew update failed.
```

**To Reproduce**
Use the installer from Github release.

**Expected behavior(s)**
Successful installation

**Screenshots**
![image](https://github.com/massalabs/station/assets/22281426/4ff89e04-41bc-4772-8099-3a95e99a0e45)

**MassaStation version**
v0.2.5

**Macbook pro M1**
- OS: macOS Ventura 13.4.1

**Comment by SlnPons** [comment]
@thomas-senechal or @Thykof do we have enough info to check this error or should we ask Moncef more details like his logs or sth?

**Comment by aoudiamoncef** [comment]
It worksssss GG @thomas-senechal 

<img width="618" alt="Screenshot 2023-07-20 at 16 55 09" src="https://github.com/massalabs/station/assets/22281426/37dbd670-e885-44b8-8d7e-42e4698a2977">
<img width="1441" alt="Screenshot 2023-07-20 at 17 10 38" src="https://github.com/massalabs/station/assets/22281426/418ac6a1-3686-4992-abab-3eadd8bccdde">
