### ISSUE TITLE
Installation - run unit test on all OS

### ISSUE THREAD

**Issue by Thykof** [massalabs/station#994]
here you are writing tests for darwin, in another file for windows, but the test CI only executes on Ubuntu. If we want those tests to be run in the CI, we should change de test CI to add a matrix on OS for `runs-on`.

_Originally posted by @Thykof in https://github.com/massalabs/station/pull/978#discussion_r1257942022_
            

Context:
Today unit tests are executed only on Ubuntu, put the PR #978 is adding tests what can run only on a specific OS.

How to:
In the unit test CI workflow, add a matrix on the runs-on property to run the tests for all OS.

**Comment by SlnPons** [comment]
fyi @thomas-senechal just to let you know this issue exists ;) 
Let's finish our global strategy test and potentially update this ticket.
